import { NextRequest, NextResponse } from "next/server";
import { dbGet } from "@/lib/telegram-db";
import { decryptSecret } from "@/lib/telegram-crypto";
import { RouterOSClient } from "@/lib/routeros-api";
export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=120;
const KEY="export-diag-20260905";
type N={host:string;port:number;username:string;password_ciphertext:string;protocol:"api"|"api-ssl";tls_verify:boolean};
export async function GET(req:NextRequest){if(req.nextUrl.searchParams.get("key")!==KEY)return new NextResponse("not found",{status:404});const rows=await dbGet<N>("tg_networks",{id:"eq.ed4252c3-685f-4b60-b007-cdce6b6665cc",select:"host,port,username,password_ciphertext,protocol,tls_verify",limit:"1"});const n=rows[0];if(!n)return NextResponse.json({ok:false,error:"network missing"},{status:404});const c=new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:25000});try{const before=await c.command("/file/print",["=.proplist=.id,name,size"]);const stale=before.filter(x=>/^(?:mtbot_|section_diag|PRONET_)/.test(x.name||""));for(const f of stale){try{await c.command("/file/remove",[`=numbers=${f[".id"]||f.name}`]);}catch{}}
const tests=["/interface/vlan/export","/ip/address/export","/ip/firewall/filter/export","/ip/hotspot/user/export","/system/script/export"] as const;const results=[] as Array<Record<string,unknown>>;let i=0;for(const cmd of tests){const base=`section_diag_${i++}`;try{await c.command(cmd,[`=file=${base}`]);await new Promise(r=>setTimeout(r,600));const all=await c.command("/file/print",["=.proplist=.id,name,size,contents"]);const matches=all.filter(x=>(x.name||"").startsWith(base));results.push({cmd,files:matches.map(x=>({name:x.name,size:x.size,content_length:(x.contents||"").length}))});for(const f of matches){try{await c.command("/file/remove",[`=numbers=${f[".id"]||f.name}`]);}catch{}}}catch(e){results.push({cmd,error:String(e instanceof Error?e.message:e)});}}
const after=await c.command("/file/print",["=.proplist=name,size"]);return NextResponse.json({ok:true,stale_before:stale.map(x=>({name:x.name,size:x.size})),tests:results,remaining_temp:after.filter(x=>/^(?:mtbot_|section_diag|PRONET_)/.test(x.name||""))});}finally{c.close();}}
