import { decryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert, dbPatch } from "./telegram-db";
import { normalizeLocalText } from "./telegram-nlu-v2";
import { RouterOSClient } from "./routeros-api";
import type { TgUpdate } from "./telegram-extra";

type Network={id:string;telegram_user_id:number;label:string;connection_mode:"direct"|"agent";host?:string|null;port?:number|null;username?:string|null;password_ciphertext?:string|null;protocol:"api"|"api-ssl";tls_verify:boolean;identity?:string|null;router_os_version?:string|null;agent_last_seen_at?:string|null};
type BotUser={telegram_user_id:number;active_network_id?:string|null};
type AlertKind="router_unreachable"|"agent_offline"|"internet_down"|"high_ping"|"packet_loss"|"cpu_high"|"ram_high"|"interface_down";
type AlertRule={id:string;telegram_user_id:number;network_id:string;kind:AlertKind;target?:string|null;threshold?:number|null;enabled:boolean;consecutive_failures:number;consecutive_recoveries:number;cooldown_minutes:number;config:Record<string,unknown>;created_at:string;updated_at:string};
type AlertState={rule_id:string;current_state:string;bad_count:number;good_count:number;last_value:Record<string,unknown>;active_since?:string|null;last_checked_at?:string|null;last_notified_at?:string|null;last_error?:string|null;updated_at:string};
type Evaluation={available:boolean;bad?:boolean;title:string;detail:string;recovery:string;value:Record<string,unknown>;error?:string};
type DirectMetrics={reachable:boolean;error?:string;cpu?:number;ram?:number;pingReplies?:number;pingCount?:number;avgPingMs?:number;lossPct?:number;interfaces:Map<string,{running:boolean;disabled:boolean;name:string}>;vlans:Map<number,{running:boolean;disabled:boolean;name:string}>};

function botToken(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function send(chatId:number,text:string){const r=await fetch(`https://api.telegram.org/bot${botToken()}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true}),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
function clientFor(n:Network){if(n.connection_mode!=="direct"||!n.host||!n.port||!n.username||!n.password_ciphertext)throw new Error("Direct API credentials are incomplete");return new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:20000});}
function parseTimeMs(value:string|undefined){if(!value)return null;const s=value.trim();let total=0;let found=false;for(const m of s.matchAll(/([0-9.]+)(ms|us|µs|s)/g)){const n=Number(m[1]);if(!Number.isFinite(n))continue;found=true;if(m[2]==="s")total+=n*1000;else if(m[2]==="ms")total+=n;else total+=n/1000;}return found?total:null;}
function formatDuration(ms:number){const min=Math.max(1,Math.round(ms/60000));if(min<60)return `${min} دقيقة`;const h=Math.floor(min/60),m=min%60;return m?`${h} ساعة و${m} دقيقة`:`${h} ساعة`;}
function label(kind:AlertKind){return({router_unreachable:"الوصول للراوتر",agent_offline:"Agent",internet_down:"الإنترنت",high_ping:"Ping مرتفع",packet_loss:"Packet loss",cpu_high:"CPU",ram_high:"RAM",interface_down:"Interface/VLAN"} as Record<AlertKind,string>)[kind];}
function activeNetwork(uid:number){return dbGet<BotUser>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id",limit:"1"}).then(async u=>{const id=u[0]?.active_network_id;if(!id)return null;return (await dbGet<Network>("tg_networks",{id:`eq.${id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;});}

async function ensureRule(uid:number,networkId:string,kind:AlertKind,opts:{target?:string|null;threshold?:number|null;failures?:number;recoveries?:number;cooldown?:number;config?:Record<string,unknown>}={}){
  const target=opts.target??null;const q:Record<string,string>={network_id:`eq.${networkId}`,kind:`eq.${kind}`,select:"*",limit:"20"};
  const rows=await dbGet<AlertRule>("tg_alert_rules",q);const old=rows.find(r=>(r.target??null)===target);
  const patch={enabled:true,threshold:opts.threshold??old?.threshold??null,consecutive_failures:opts.failures??old?.consecutive_failures??2,consecutive_recoveries:opts.recoveries??old?.consecutive_recoveries??1,cooldown_minutes:opts.cooldown??old?.cooldown_minutes??30,config:opts.config??old?.config??{},updated_at:new Date().toISOString()};
  if(old){await dbPatch("tg_alert_rules",patch,{id:`eq.${old.id}`,telegram_user_id:`eq.${uid}`});return old.id;}
  const created=await dbInsert<AlertRule>("tg_alert_rules",{telegram_user_id:uid,network_id:networkId,kind,target,...patch},"*");return created[0]?.id||"";
}
async function disableRules(uid:number,networkId:string,kind?:AlertKind){const filters:Record<string,string>={telegram_user_id:`eq.${uid}`,network_id:`eq.${networkId}`,enabled:"eq.true",select:"id,kind,target"};if(kind)filters.kind=`eq.${kind}`;const rows=await dbGet<AlertRule>("tg_alert_rules",filters);for(const r of rows)await dbPatch("tg_alert_rules",{enabled:false,updated_at:new Date().toISOString()},{id:`eq.${r.id}`});return rows.length;}

function defaultRules(n:Network){if(n.connection_mode==="agent")return [{kind:"agent_offline" as AlertKind,failures:2,recoveries:1}];return[
  {kind:"router_unreachable" as AlertKind,failures:2,recoveries:1},
  {kind:"internet_down" as AlertKind,failures:2,recoveries:1},
  {kind:"high_ping" as AlertKind,threshold:350,failures:3,recoveries:2},
  {kind:"packet_loss" as AlertKind,threshold:50,failures:3,recoveries:2},
  {kind:"cpu_high" as AlertKind,threshold:90,failures:3,recoveries:2},
  {kind:"ram_high" as AlertKind,threshold:95,failures:3,recoveries:2},
];}

async function collectDirect(n:Network,rules:AlertRule[]):Promise<DirectMetrics>{const out:DirectMetrics={reachable:false,interfaces:new Map(),vlans:new Map()};let c:RouterOSClient|undefined;try{c=clientFor(n);const resource=await c.command("/system/resource/print",["=.proplist=cpu-load,free-memory,total-memory"]);out.reachable=true;const r=resource[0]||{};out.cpu=Number(r["cpu-load"]||0);const total=Number(r["total-memory"]||0),free=Number(r["free-memory"]||0);out.ram=total?Math.round((1-free/total)*100):0;
    if(rules.some(x=>["internet_down","high_ping","packet_loss"].includes(x.kind))){try{const rows=await c.command("/ping",["=address=8.8.8.8","=count=4"]);const times=rows.map(x=>parseTimeMs(x.time)).filter((x):x is number=>x!==null);out.pingCount=4;out.pingReplies=times.length;out.lossPct=Math.round((1-times.length/4)*100);out.avgPingMs=times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length):0;}catch{out.pingCount=4;out.pingReplies=0;out.lossPct=100;out.avgPingMs=0;}}
    const targets=[...new Set(rules.filter(x=>x.kind==="interface_down"&&x.target).map(x=>String(x.target)))];for(const target of targets){if(target.startsWith("vlan:")){const id=Number(target.slice(5));try{const rows=await c.command("/interface/vlan/print",["=.proplist=name,vlan-id,running,disabled",`?vlan-id=${id}`]);const row=rows[0];if(row)out.vlans.set(id,{name:row.name||`VLAN ${id}`,running:row.running==="true",disabled:row.disabled==="true"});}catch{}}else{try{const rows=await c.command("/interface/print",["=.proplist=name,running,disabled",`?name=${target}`]);const row=rows[0];if(row)out.interfaces.set(target,{name:row.name||target,running:row.running==="true",disabled:row.disabled==="true"});}catch{}}}
    return out;
  }catch(e){out.error=e instanceof Error?e.message:String(e);return out;}finally{c?.close();}}

function evaluate(rule:AlertRule,n:Network,m?:DirectMetrics):Evaluation{const threshold=Number(rule.threshold||0);if(n.connection_mode==="agent"){const age=n.agent_last_seen_at?Date.now()-new Date(n.agent_last_seen_at).getTime():Number.POSITIVE_INFINITY;const bad=age>90_000;return{available:true,bad,title:"Agent غير متصل",detail:`آخر اتصال بالـAgent منذ ${Number.isFinite(age)?formatDuration(age):"وقت غير معروف"}.`,recovery:"عاد Agent للاتصال بالسحابة.",value:{age_ms:Number.isFinite(age)?age:null,last_seen:n.agent_last_seen_at||null}};}
  if(!m)return{available:false,title:label(rule.kind),detail:"",recovery:"",value:{},error:"metrics unavailable"};
  if(rule.kind==="router_unreachable")return{available:true,bad:!m.reachable,title:"تعذر الوصول للراوتر",detail:m.error?`فشل اتصال Cloud بالـRouterOS API: ${m.error.slice(0,180)}`:"الراوتر لم يرد على API.",recovery:"عاد الاتصال بالراوتر من السحابة.",value:{reachable:m.reachable,error:m.error||null}};
  if(!m.reachable)return{available:false,title:label(rule.kind),detail:"",recovery:"",value:{},error:m.error||"router unreachable"};
  if(rule.kind==="internet_down"){const replies=m.pingReplies??0;return{available:true,bad:replies===0,title:"الإنترنت لا يرد",detail:`الراوتر لم يحصل على أي رد من 8.8.8.8 (${replies}/${m.pingCount??4}).`,recovery:"عاد الإنترنت للرد من الراوتر.",value:{replies,count:m.pingCount,loss_pct:m.lossPct,avg_ping_ms:m.avgPingMs}};}
  if(rule.kind==="high_ping")return{available:true,bad:(m.avgPingMs??0)>threshold,title:"Ping مرتفع",detail:`متوسط Ping الحالي ${m.avgPingMs??0}ms، والحد ${threshold}ms.`,recovery:`عاد Ping تحت ${threshold}ms.`,value:{avg_ping_ms:m.avgPingMs,threshold}};
  if(rule.kind==="packet_loss")return{available:true,bad:(m.lossPct??0)>threshold,title:"Packet loss مرتفع",detail:`الفقد الحالي ${m.lossPct??0}%، والحد ${threshold}%.`,recovery:`عاد Packet loss تحت ${threshold}%.`,value:{loss_pct:m.lossPct,threshold}};
  if(rule.kind==="cpu_high")return{available:true,bad:(m.cpu??0)>threshold,title:"استخدام CPU مرتفع",detail:`CPU الآن ${m.cpu??0}%، والحد ${threshold}%.`,recovery:`عاد CPU تحت ${threshold}%.`,value:{cpu:m.cpu,threshold}};
  if(rule.kind==="ram_high")return{available:true,bad:(m.ram??0)>threshold,title:"استخدام RAM مرتفع",detail:`RAM الآن ${m.ram??0}%، والحد ${threshold}%.`,recovery:`عادت RAM تحت ${threshold}%.`,value:{ram:m.ram,threshold}};
  if(rule.kind==="interface_down"){const t=String(rule.target||"");if(t.startsWith("vlan:")){const id=Number(t.slice(5)),x=m.vlans.get(id);if(!x)return{available:true,bad:true,title:`VLAN ${id} غير موجود`,detail:`لم أجد VLAN ID ${id} على الراوتر.`,recovery:`عاد VLAN ${id} للظهور والعمل.`,value:{target:t,found:false}};return{available:true,bad:x.disabled||!x.running,title:`VLAN ${id} متوقف`,detail:`${x.name}: running=${x.running?"yes":"no"}, disabled=${x.disabled?"yes":"no"}.`,recovery:`VLAN ${id} عاد Running.`,value:{target:t,name:x.name,running:x.running,disabled:x.disabled}};}const x=m.interfaces.get(t);if(!x)return{available:true,bad:true,title:`Interface ${t} غير موجود`,detail:`لم أجد Interface باسم ${t}.`,recovery:`عاد Interface ${t} للظهور والعمل.`,value:{target:t,found:false}};return{available:true,bad:x.disabled||!x.running,title:`Interface ${t} متوقف`,detail:`running=${x.running?"yes":"no"}, disabled=${x.disabled?"yes":"no"}.`,recovery:`Interface ${t} عاد Running.`,value:{target:t,running:x.running,disabled:x.disabled}};}
  return{available:false,title:label(rule.kind),detail:"",recovery:"",value:{},error:"unsupported rule"};}

async function stateFor(ruleId:string){return (await dbGet<AlertState>("tg_alert_state",{rule_id:`eq.${ruleId}`,select:"*",limit:"1"}))[0]??null;}
async function saveState(ruleId:string,old:AlertState|null,patch:Record<string,unknown>){const payload={...patch,updated_at:new Date().toISOString()};if(old)await dbPatch("tg_alert_state",payload,{rule_id:`eq.${ruleId}`});else await dbInsert("tg_alert_state",{rule_id:ruleId,current_state:"unknown",bad_count:0,good_count:0,last_value:{},...payload});}
async function transition(rule:AlertRule,n:Network,ev:Evaluation){const now=new Date(),old=await stateFor(rule.id);if(!ev.available){await saveState(rule.id,old,{last_checked_at:now.toISOString(),last_error:ev.error||"unavailable"});return;}
  const wasAlert=old?.current_state==="alert";if(ev.bad){const bad=(old?.bad_count||0)+1;const shouldAlert=!wasAlert&&bad>=rule.consecutive_failures;const activeSince=wasAlert?(old?.active_since||now.toISOString()):(shouldAlert?now.toISOString():old?.active_since||null);if(shouldAlert){await send(rule.telegram_user_id,`🔴 <b>${esc(n.identity||n.label)} • تنبيه</b>\n━━━━━━━━━━━━━━━━━━\n⚠️ <b>${esc(ev.title)}</b>\n${esc(ev.detail)}\n\n✅ تم التأكيد بعد <b>${rule.consecutive_failures}</b> فحوص متتالية.\n🔕 لن أكرر نفس التنبيه حتى تتغير الحالة أو ترجع طبيعية.`);}await saveState(rule.id,old,{current_state:shouldAlert||wasAlert?"alert":(old?.current_state||"unknown"),bad_count:bad,good_count:0,last_value:ev.value,active_since:activeSince,last_checked_at:now.toISOString(),last_notified_at:shouldAlert?now.toISOString():old?.last_notified_at||null,last_error:null});return;}
  const good=(old?.good_count||0)+1;if(wasAlert&&good>=rule.consecutive_recoveries){const since=old?.active_since?new Date(old.active_since).getTime():now.getTime();await send(rule.telegram_user_id,`🟢 <b>${esc(n.identity||n.label)} • عادت طبيعية</b>\n━━━━━━━━━━━━━━━━━━\n✅ ${esc(ev.recovery)}\n⏱ مدة الحالة تقريبًا: <b>${esc(formatDuration(now.getTime()-since))}</b>.`);await saveState(rule.id,old,{current_state:"normal",bad_count:0,good_count:good,last_value:ev.value,active_since:null,last_checked_at:now.toISOString(),last_notified_at:now.toISOString(),last_error:null});return;}
  await saveState(rule.id,old,{current_state:wasAlert?"alert":"normal",bad_count:0,good_count:good,last_value:ev.value,last_checked_at:now.toISOString(),last_error:null});}

export async function runAlertChecksSafe(){const rules=await dbGet<AlertRule>("tg_alert_rules",{enabled:"eq.true",select:"*",order:"network_id.asc",limit:"200"});if(!rules.length)return[];const byNetwork=new Map<string,AlertRule[]>();for(const r of rules){const a=byNetwork.get(r.network_id)||[];a.push(r);byNetwork.set(r.network_id,a);}const results:Array<{network_id:string;checked:number}>=[];
  for(const [networkId,networkRules] of byNetwork){const n=(await dbGet<Network>("tg_networks",{id:`eq.${networkId}`,select:"*",limit:"1"}))[0];if(!n)continue;const metrics=n.connection_mode==="direct"?await collectDirect(n,networkRules):undefined;for(const rule of networkRules){try{await transition(rule,n,evaluate(rule,n,metrics));}catch(e){console.error("alert rule failed",rule.id,e);}}results.push({network_id:networkId,checked:networkRules.length});}return results;}

function latinDigits(s:string){return s.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)));}
function numberIn(s:string){const m=latinDigits(s).match(/\d{1,4}/);return m?Number(m[0]):null;}
function alertKindFrom(n:string):AlertKind|null{if(/(?:بنج|بينق|ping)/i.test(n))return"high_ping";if(/(?:packet\s*loss|فقد|فاقد|loss)/i.test(n))return"packet_loss";if(/(?:cpu|المعالج|بروسيسر)/i.test(n))return"cpu_high";if(/(?:ram|رام|الذاكره|الذاكرة|memory)/i.test(n))return"ram_high";if(/(?:agent)/i.test(n))return"agent_offline";if(/(?:راوتر.*(?:ما يرد|فصل|اوفلاين)|router.*(?:offline|unreachable))/i.test(n))return"router_unreachable";if(/(?:نت|انترنت|الانترنت|internet).*(?:فصل|انقطع|طاح|down|offline)|(?:فصل|انقطع|طاح).*(?:نت|انترنت|الانترنت)/i.test(n))return"internet_down";return null;}

async function listAlerts(chatId:number,uid:number,n:Network){const rules=await dbGet<AlertRule>("tg_alert_rules",{telegram_user_id:`eq.${uid}`,network_id:`eq.${n.id}`,select:"*",order:"created_at.asc",limit:"50"});if(!rules.length){await send(chatId,`🔔 لا توجد تنبيهات مفعلة على <b>${esc(n.identity||n.label)}</b>.\n\nأرسل: <code>شغل التنبيهات</code>`);return;}const states=await dbGet<AlertState>("tg_alert_state",{select:"*",limit:"100"});const map=new Map(states.map(s=>[s.rule_id,s]));const lines=rules.map((r,i)=>{const st=map.get(r.id);const th=r.threshold!=null?` • حد ${r.threshold}`:"";const tgt=r.target?` • ${r.target}`:"";return`${i+1}. ${r.enabled?"🔔":"🔕"} <b>${esc(label(r.kind))}</b>${esc(th+tgt)}\n   الحالة: ${st?.current_state==="alert"?"🔴 تنبيه":st?.current_state==="normal"?"🟢 طبيعي":"⚪ لم يفحص بعد"}`;});await send(chatId,`🔔 <b>تنبيهات ${esc(n.identity||n.label)}</b>\n━━━━━━━━━━━━━━━━━━\n${lines.join("\n\n")}\n\nأمثلة:\n<code>نبهني اذا البنج فوق 250</code>\n<code>وقف تنبيه البنج</code>\n<code>نبهني اذا vlan 202 فصل</code>`);}

export async function handleTelegramAlerts(update:TgUpdate):Promise<boolean>{const m=update.message;if(!m?.from||!m.text)return false;const raw=m.text.trim(),nrm=normalizeLocalText(raw);const isList=/^(?:\/alerts|تنبيهاتي|التنبيهات|عرض التنبيهات)$/i.test(nrm);const enableAll=/(?:شغل|فعل|فعّل|enable|start).*(?:التنبيهات|تنبيهات|alerts)|^(?:\/alerts\s+on)$/i.test(nrm);const disableAll=/(?:وقف|الغ|الغي|عطل|اطف|disable|stop).*(?:التنبيهات|تنبيهات|alerts)|^(?:\/alerts\s+off)$/i.test(nrm);const isAlertPhrase=/(?:نبهني|نبّهني|تنبيه|alert|notify|راقب)/i.test(nrm);if(!isList&&!enableAll&&!disableAll&&!isAlertPhrase)return false;const net=await activeNetwork(m.from.id);if(!net){await send(m.chat.id,"📭 لا توجد شبكة نشطة.");return true;}
  if(isList){await listAlerts(m.chat.id,m.from.id,net);return true;}if(enableAll){for(const r of defaultRules(net))await ensureRule(m.from.id,net.id,r.kind,{threshold:"threshold" in r?r.threshold:null,failures:r.failures,recoveries:r.recoveries});await send(m.chat.id,`✅ <b>فعّلت التنبيهات الذكية على ${esc(net.identity||net.label)}</b>\nلن أنبه من قراءة واحدة؛ كل Rule تحتاج تأكيدًا بعد عدة فحوص، ولن أكرر نفس المشكلة حتى تتعافى.`);return true;}if(disableAll){const count=await disableRules(m.from.id,net.id);await send(m.chat.id,`🔕 أوقفت <b>${count}</b> تنبيه على ${esc(net.identity||net.label)}.`);return true;}
  const wantsOff=/(?:وقف|الغ|الغي|عطل|اطف|disable|stop)/i.test(nrm);let kind=alertKindFrom(nrm);let target:string|null=null;if(/(?:vlan|فيلان)/i.test(nrm)){const id=numberIn(nrm);if(id){kind="interface_down";target=`vlan:${id}`;}}else{const im=raw.match(/(?:interface|انترفيس|واجهه|واجهة)\s+([\w.@:+-]{2,128})/iu);if(im){kind="interface_down";target=im[1];}}
  if(!kind){await send(m.chat.id,"🔔 فهمت أنك تريد تنبيه، لكن لم أحدد الشرط بأمان.\nجرّب مثلًا: <code>نبهني اذا البنج فوق 250</code> أو <code>نبهني اذا النت فصل</code>.");return true;}if(wantsOff){const count=await disableRules(m.from.id,net.id,kind);await send(m.chat.id,`🔕 أوقفت تنبيه <b>${esc(label(kind))}</b>${count?".":" (لم يكن مفعّلًا)."}`);return true;}
  let threshold:number|null=null;if(["high_ping","packet_loss","cpu_high","ram_high"].includes(kind)){threshold=numberIn(nrm);if(threshold==null)threshold=kind==="high_ping"?350:kind==="packet_loss"?50:kind==="cpu_high"?90:95;if((kind==="cpu_high"||kind==="ram_high"||kind==="packet_loss")&&(threshold<1||threshold>100)){await send(m.chat.id,"⚠️ الحد يجب أن يكون بين 1 و100%.");return true;}}
  const failures=kind==="high_ping"||kind==="packet_loss"||kind==="cpu_high"||kind==="ram_high"?3:2;await ensureRule(m.from.id,net.id,kind,{target,threshold,failures,recoveries:kind==="high_ping"||kind==="packet_loss"?2:1});await send(m.chat.id,`✅ تم تفعيل تنبيه <b>${esc(label(kind))}</b> على ${esc(net.identity||net.label)}${threshold!=null?`\n🎚 الحد: <b>${threshold}${kind==="high_ping"?"ms":"%"}</b>`:""}${target?`\n🎯 الهدف: <code>${esc(target)}</code>`:""}\n🛡 لن يتم التنبيه إلا بعد <b>${failures}</b> فحوص سيئة متتالية.`);return true;}
