import { decryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert } from "./telegram-db";
import { RouterOSClient } from "./routeros-api";
import type { TgUpdate } from "./telegram-extra";

type User={telegram_user_id:number;active_network_id?:string|null};
type Network={id:string;telegram_user_id:number;label:string;connection_mode:"direct"|"agent";host?:string|null;port?:number|null;username?:string|null;password_ciphertext?:string|null;protocol:"api"|"api-ssl";tls_verify:boolean;identity?:string|null;router_os_version?:string|null;agent_last_seen_at?:string|null};
type UsageRow={user:string;address:string;server:string;total:number};
export type OpsKind="logs"|"interfaces"|"dhcp"|"hotspot"|"top_usage"|"wan"|"routes"|"dns"|"firewall"|"queues";
function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function send(chatId:number,text:string){const r=await fetch(`https://api.telegram.org/bot${token()}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text:text.slice(0,4000),parse_mode:"HTML"}),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
async function context(uid:number){const u=await dbGet<User>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id",limit:"1"});if(!u[0]?.active_network_id)return null;const n=await dbGet<Network>("tg_networks",{id:`eq.${u[0].active_network_id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"});return n[0]??null;}
function client(n:Network){if(n.connection_mode!=="direct"||!n.host||!n.port||!n.username||!n.password_ciphertext)throw new Error("Direct API credentials are incomplete");return new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:16000,maxLifetimeMs:90000});}
function bytes(n:number){if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`;}
function num(v:unknown){const n=Number(v||0);return Number.isFinite(n)?n:0;}

async function queueAgent(n:Network,uid:number,chatId:number,kind:OpsKind){const online=n.agent_last_seen_at?Date.now()-new Date(n.agent_last_seen_at).getTime()<60_000:false;const waiting=await send(chatId,`${online?"⏳":"🟠"} <b>${esc(n.identity||n.label)}</b>\n${online?"جاري تنفيذ القراءة عبر Agent…":"Agent غير ظاهر الآن؛ وضعت الطلب في الانتظار."}`);await dbInsert("tg_agent_commands",{network_id:n.id,telegram_user_id:uid,chat_id:chatId,reply_message_id:waiting.message_id,kind,payload:{},status:"pending"});}

export async function handleTelegramOps(update:TgUpdate,kind:OpsKind){const m=update.message;if(!m?.from)return false;const n=await context(m.from.id);if(!n){await send(m.chat.id,"📭 لا توجد شبكة نشطة.");return true;}if(n.connection_mode==="agent"){await queueAgent(n,m.from.id,m.chat.id,kind);return true;}const c=client(n);
 try{
  if(kind==="logs"){const rows=await c.command("/log/print",["=.proplist=time,topics,message"]);const last=rows.slice(-25).reverse();await send(m.chat.id,`🧾 <b>${esc(n.identity||n.label)} • آخر السجلات</b>\n━━━━━━━━━━━━━━━━━━\n${last.map((r,i)=>`${i+1}. <b>${esc(r.time||"-")}</b> • ${esc(r.topics||"-")}\n${esc(r.message||"-")}`).join("\n\n")||"لا توجد سجلات."}`);return true;}
  if(kind==="interfaces"){const rows=await c.command("/interface/print",["=.proplist=name,type,running,disabled,actual-mtu"]);const running=rows.filter(r=>r.running==="true"&&r.disabled!=="true").length;await send(m.chat.id,`🔌 <b>واجهات الراوتر</b>\n━━━━━━━━━━━━━━━━━━\nالإجمالي: <b>${rows.length}</b> • Running: <b>${running}</b>\n\n${rows.slice(0,60).map(r=>`${r.disabled==="true"?"⛔":r.running==="true"?"🟢":"⚪"} <b>${esc(r.name||"-")}</b> • ${esc(r.type||"-")} • MTU ${esc(r["actual-mtu"]||"-")}`).join("\n")}${rows.length>60?`\n… +${rows.length-60}`:""}`);return true;}
  if(kind==="dhcp"){const rows=await c.command("/ip/dhcp-server/lease/print",["=.proplist=address,mac-address,host-name,status,last-seen,server,disabled"]);const bound=rows.filter(r=>r.status==="bound").length;await send(m.chat.id,`📬 <b>DHCP Leases</b>\n━━━━━━━━━━━━━━━━━━\n🟢 Bound: <b>${bound}</b> / ${rows.length}\n\n${rows.filter(r=>r.status==="bound").slice(0,50).map((r,i)=>`${i+1}. ${esc(r.address||"-")} • <code>${esc(r["mac-address"]||"-")}</code>${r["host-name"]?` • ${esc(r["host-name"])}`:""}`).join("\n")||"لا توجد leases مرتبطة الآن."}`);return true;}
  if(kind==="hotspot"){const servers=await c.command("/ip/hotspot/print",["=.proplist=name,interface,disabled,profile"]);const active=await c.command("/ip/hotspot/active/print",["=.proplist=user,address,server,uptime"]);const users=await c.command("/ip/hotspot/user/print",["=.proplist=name,profile,disabled"]);await send(m.chat.id,`📡 <b>Hotspot Overview</b>\n━━━━━━━━━━━━━━━━━━\n🧩 Servers: <b>${servers.length}</b>\n👥 Active: <b>${active.length}</b>\n🎫 Local users: <b>${users.length}</b>\n🚫 Disabled users: <b>${users.filter(x=>x.disabled==="true").length}</b>\n\n${servers.slice(0,20).map(s=>`• ${s.disabled==="true"?"⛔":"🟢"} <b>${esc(s.name||"-")}</b> • ${esc(s.interface||"-")}`).join("\n")}`);return true;}
  if(kind==="top_usage"){const rows=await c.command("/ip/hotspot/active/print",["=.proplist=user,address,server,uptime,bytes-in,bytes-out"]);const ranked:UsageRow[]=rows.map((r):UsageRow=>({user:r.user||"-",address:r.address||"-",server:r.server||"-",total:num(r["bytes-in"])+num(r["bytes-out"])})).sort((a,b)=>b.total-a.total).slice(0,20);await send(m.chat.id,`🏆 <b>أعلى المتصلين استهلاكًا في الجلسة الحالية</b>\n━━━━━━━━━━━━━━━━━━\n${ranked.map((r,i)=>`${i+1}. <code>${esc(r.user)}</code> • <b>${bytes(r.total)}</b>\n   ${esc(r.address)} • ${esc(r.server)}`).join("\n\n")||"لا يوجد مستخدمون متصلون."}`);return true;}
  if(kind==="wan"){let ppp:Record<string,string>[]=[];let dhcp:Record<string,string>[]=[];let routes:Record<string,string>[]=[];try{ppp=await c.command("/interface/pppoe-client/print",["=.proplist=name,interface,running,disabled"]);}catch{}try{dhcp=await c.command("/ip/dhcp-client/print",["=.proplist=interface,status,address,gateway,disabled"]);}catch{}try{routes=await c.command("/ip/route/print",["=.proplist=dst-address,gateway,distance,active,disabled",'?dst-address=0.0.0.0/0']);}catch{}const pppOn=ppp.filter(x=>x.disabled!=="true"),dhcpOn=dhcp.filter(x=>x.disabled!=="true"),routeOn=routes.filter(x=>x.disabled!=="true");const lines=[...pppOn.map(x=>`${x.running==="true"?"🟢":"⚪"} PPPoE <b>${esc(x.name||"-")}</b> • ${esc(x.interface||"-")}`),...dhcpOn.map(x=>`${x.status==="bound"?"🟢":"⚪"} DHCP <b>${esc(x.interface||"-")}</b> • ${esc(x.status||"-")}${x.address?` • ${esc(x.address)}`:""}`)];await send(m.chat.id,`🌐 <b>${esc(n.identity||n.label)} • WAN Overview</b>\n━━━━━━━━━━━━━━━━━━\n🔗 PPPoE: <b>${pppOn.filter(x=>x.running==="true").length}/${pppOn.length}</b> Running\n📥 DHCP WAN: <b>${dhcpOn.filter(x=>x.status==="bound").length}/${dhcpOn.length}</b> Bound\n🛣 Default routes: <b>${routeOn.filter(x=>x.active==="true").length}/${routeOn.length}</b> Active\n\n${lines.join("\n")||"لم أجد PPPoE أو DHCP clients مفعلة."}`);return true;}
  if(kind==="routes"){const routes=await c.command("/ip/route/print",["=.proplist=dst-address,gateway,distance,active,disabled,dynamic",'?dst-address=0.0.0.0/0']);await send(m.chat.id,`🛣 <b>Default Routes</b>\n━━━━━━━━━━━━━━━━━━\n${routes.map(x=>`${x.disabled==="true"?"⛔":x.active==="true"?"🟢":"⚪"} <b>${esc(x["dst-address"]||"0.0.0.0/0")}</b> → ${esc(x.gateway||"-")} • distance ${esc(x.distance||"-")}${x.dynamic==="true"?" • dynamic":""}`).join("\n")||"لا توجد Default Route."}\n\nℹ️ لم أسحب جدول Routes كاملًا حتى لا أضغط راوترات BGP الكبيرة.`);return true;}
  if(kind==="dns"){const rows=await c.command("/ip/dns/print",["=.proplist=servers,dynamic-servers,allow-remote-requests,cache-size"]);const d=rows[0]||{};let resolved=false;try{const ping=await c.command("/ping",["=address=google.com","=count=1"]);resolved=ping.some(x=>Boolean(x.time));}catch{}await send(m.chat.id,`🔤 <b>DNS Overview</b>\n━━━━━━━━━━━━━━━━━━\n🧭 Static servers: <code>${esc(d.servers||"-")}</code>\n🔄 Dynamic servers: <code>${esc(d["dynamic-servers"]||"-")}</code>\n🏠 Remote requests: <b>${esc(d["allow-remote-requests"]||"false")}</b>\n🧪 Resolve/Ping google.com: ${resolved?"🟢 يعمل":"🔴 فشل"}`);return true;}
  if(kind==="firewall"){const filter=await c.command("/ip/firewall/filter/print",["=.proplist=.id"]);const nat=await c.command("/ip/firewall/nat/print",["=.proplist=.id"]);const mangle=await c.command("/ip/firewall/mangle/print",["=.proplist=.id"]);let raw:Record<string,string>[]=[];try{raw=await c.command("/ip/firewall/raw/print",["=.proplist=.id"]);}catch{}await send(m.chat.id,`🛡 <b>Firewall Summary</b>\n━━━━━━━━━━━━━━━━━━\n🧱 Filter rules: <b>${filter.length}</b>\n🔀 NAT rules: <b>${nat.length}</b>\n🧩 Mangle rules: <b>${mangle.length}</b>\n⚡ Raw rules: <b>${raw.length}</b>\n\nℹ️ لم أسحب Address Lists أو محتوى القواعد بالكامل حتى لا أضغط الراوتر أو أعرض إعدادات حساسة.`);return true;}
  const simple=await c.command("/queue/simple/print",["=.proplist=name,target,max-limit,disabled"]);let trees:Record<string,string>[]=[];try{trees=await c.command("/queue/tree/print",["=.proplist=.id"]);}catch{}await send(m.chat.id,`🚦 <b>Queues Overview</b>\n━━━━━━━━━━━━━━━━━━\nSimple queues: <b>${simple.filter(x=>x.disabled!=="true").length}/${simple.length}</b> Enabled\nQueue trees: <b>${trees.length}</b>\n\n${simple.slice(0,35).map(x=>`${x.disabled==="true"?"⛔":"🟢"} <b>${esc(x.name||"-")}</b> • ${esc(x.target||"-")} • max ${esc(x["max-limit"]||"-")}`).join("\n")||"لا توجد Simple Queues."}`);return true;
 }catch(e){await send(m.chat.id,`🔴 تعذر تنفيذ القراءة.\n<code>${esc(e instanceof Error?e.message:e)}</code>`);return true;}finally{c.close();}
}
