import { decryptSecret, encryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert, dbPatch } from "./telegram-db";
import { RouterOSClient } from "./routeros-api";
import { normalizeLocalText } from "./telegram-nlu-v2";
import { handleTelegramCardUniversal } from "./telegram-card-universal";
import type { TgUpdate } from "./telegram-extra";

type Source="hotspot"|"user-manager-v6"|"user-manager-v7";
type Operation="change_profile"|"change_password"|"delete_user";
type Network={id:string;telegram_user_id:number;label:string;connection_mode:"direct"|"agent";host?:string|null;port?:number|null;username?:string|null;password_ciphertext?:string|null;protocol:"api"|"api-ssl";tls_verify:boolean;identity?:string|null;router_os_version?:string|null};
type BotUser={telegram_user_id:number;active_network_id?:string|null};
type AdminSession={id:string;telegram_user_id:number;chat_id:number;network_id:string;operation:Operation;username:string;source?:Source|null;profiles:string[];selected_profile?:string|null;password_ciphertext?:string|null;step:string;expires_at:string;created_at:string};
type PendingAction={id:string;telegram_user_id:number;chat_id:number;network_id:string;action_type:string;target_type:string;target_value:string;preview:Record<string,unknown>;status:string;expires_at:string};
type UserResolved={source:Source;entry:Record<string,string>;active:Record<string,string>[];profiles:string[];version:string;customer?:string|null};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function tg(method:string,payload:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
function send(chatId:number,text:string,reply_markup?:unknown){return tg("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}
async function edit(chatId:number,messageId:number,text:string,reply_markup?:unknown){try{return await tg("editMessageText",{chat_id:chatId,message_id:messageId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}catch{return null;}}
async function answer(id:string,text?:string,alert=false){try{await tg("answerCallbackQuery",{callback_query_id:id,text,show_alert:alert});}catch{}}
async function del(chatId:number,messageId:number){try{await tg("deleteMessage",{chat_id:chatId,message_id:messageId});}catch{}}

async function activeNetwork(uid:number){const u=(await dbGet<BotUser>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id",limit:"1"}))[0];if(!u?.active_network_id)return null;return (await dbGet<Network>("tg_networks",{id:`eq.${u.active_network_id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}
async function exactNetwork(uid:number,id:string){return (await dbGet<Network>("tg_networks",{id:`eq.${id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}
function client(n:Network){if(n.connection_mode!=="direct"||!n.host||!n.port||!n.username||!n.password_ciphertext)throw new Error("هذه العملية تحتاج Direct API أو Privileged Agent مفعّل.");return new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:25000});}
function disabled(v?:string){return v==="true"||v==="yes";}
function sourceLabel(s:Source){return s==="hotspot"?"Hotspot Local User":s==="user-manager-v6"?"User Manager v6":"User Manager v7";}
function currentProfile(r:UserResolved){return r.entry.profile||r.entry["actual-profile"]||r.entry.group||"-";}

async function audit(p:{telegram_user_id:number;chat_id:number;network_id:string;pending_action_id?:string|null;action_type:string;target_value:string;phase:string;details?:Record<string,unknown>}){await dbInsert("tg_action_audit",{telegram_user_id:p.telegram_user_id,chat_id:p.chat_id,network_id:p.network_id,pending_action_id:p.pending_action_id||null,action_type:p.action_type,target_type:"user",target_value:p.target_value,phase:p.phase,details:p.details||{}});}

async function resolveUser(c:RouterOSClient,username:string):Promise<UserResolved|null>{
  const active=await c.command("/ip/hotspot/active/print",["=.proplist=.id,user,address,mac-address,server,uptime,bytes-in,bytes-out",`?user=${username}`]);
  const res=await c.command("/system/resource/print",["=.proplist=version"]);const version=res[0]?.version||"";const major=Number(/^\d+/.exec(version)?.[0]||0);
  const local=await c.command("/ip/hotspot/user/print",["=.proplist=.id,name,profile,disabled,comment",`?name=${username}`]);
  if(local[0]){const p=await c.command("/ip/hotspot/user/profile/print",["=.proplist=name"]);return{source:"hotspot",entry:local[0],active,profiles:p.map(x=>x.name).filter(Boolean),version};}
  if(major>=7){try{const rows=await c.command("/user-manager/user/print",["=.proplist=.id,name,group,disabled,comment",`?name=${username}`]);if(rows[0]){const p=await c.command("/user-manager/profile/print",["=.proplist=name"]);let actual="";try{const mon=await c.command("/user-manager/user/monitor",[`=numbers=${username}`]);actual=mon[0]?.["actual-profile"]||"";}catch{}if(actual)rows[0]["actual-profile"]=actual;return{source:"user-manager-v7",entry:rows[0],active,profiles:p.map(x=>x.name).filter(Boolean),version};}}catch{}
  }else{try{const rows=await c.command("/tool/user-manager/user/print",["=.proplist=.id,username,actual-profile,disabled,customer",`?username=${username}`]);if(rows[0]){const p=await c.command("/tool/user-manager/profile/print",["=.proplist=name"]);let customer=rows[0].customer||"";if(!customer)try{const cs=await c.command("/tool/user-manager/customer/print");customer=cs[0]?.login||cs[0]?.name||cs[0]?.username||"admin";}catch{customer="admin";}return{source:"user-manager-v6",entry:rows[0],active,profiles:p.map(x=>x.name).filter(Boolean),version,customer};}}catch{}
  return null;
}

function cleanUsername(v:string|undefined|null){if(!v)return null;const x=v.trim().replace(/^["'«]+|["'»،,.!?]+$/g,"");return /^[\p{L}\p{N}_.@:+-]{2,128}$/u.test(x)?x:null;}
function usernameFrom(raw:string){const quoted=cleanUsername(raw.match(/["'«]([^"'»]{2,128})["'»]/u)?.[1]);if(quoted)return quoted;const m=raw.match(/(?:مستخدم|المستخدم|يوزر|اليوزر|كرت|الكرت|مشترك|user|card|account)\s*(?:رقم|اسم|اسمه|name|number)?\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{2,128})/iu)?.[1];if(m)return cleanUsername(m);const cmd=raw.trim().split(/\s+/);if(cmd[0]?.startsWith("/")&&cmd[1]&&!/^(?:profile|password|passwd|delete|remove|info)$/i.test(cmd[1]))return cleanUsername(cmd[1]);return null;}
function profileHint(raw:string,username:string){const after=raw.slice(Math.max(0,raw.toLowerCase().indexOf(username.toLowerCase())+username.length));const m=after.match(/(?:الى|إلى|الي|على|لباقة|لباقه|to|profile|plan)\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{1,128})/iu)?.[1];return m?.trim()||null;}
function parseRequest(raw:string):{operation:Operation;username:string;profile_hint?:string|null}|null{
  const n=normalizeLocalText(raw);let op:Operation|null=null;
  if(/(?:احذف|حذف|امسح|مسح|شيل|ازل|إزالة|remove|delete)\s*(?:لي\s*)?(?:المستخدم|مستخدم|اليوزر|يوزر|الكرت|كرت|user|card|account)/iu.test(n)||/^\/(?:deleteuser|deluser|removeuser)\b/i.test(raw))op="delete_user";
  else if(/(?:غير|غيّر|بدل|حوّل|حول|change|switch)\s*(?:لي\s*)?(?:الباقه|الباقة|البروفايل|بروفايل|profile|plan)/iu.test(n)||/^\/(?:profile|setprofile)\b/i.test(raw)||/^\/user\s+profile\b/i.test(raw))op="change_profile";
  else if(/(?:غير|غيّر|بدل|reset|change)\s*(?:لي\s*)?(?:كلمه\s*المرور|كلمة\s*المرور|الباسورد|باسورد|password|passwd|pass)/iu.test(n)||/^\/(?:password|passwd|setpass)\b/i.test(raw)||/^\/user\s+(?:password|passwd)\b/i.test(raw))op="change_password";
  if(!op)return null;
  let username=usernameFrom(raw);
  const parts=raw.trim().split(/\s+/);
  if(!username&&/^\/user$/i.test(parts[0]||"")&&parts[2])username=cleanUsername(parts[2]);
  if(!username&&/^\/(?:profile|setprofile|password|passwd|setpass|deleteuser|deluser|removeuser)$/i.test(parts[0]||"")&&parts[1])username=cleanUsername(parts[1]);
  if(!username)return null;
  return{operation:op,username,profile_hint:op==="change_profile"?profileHint(raw,username):null};
}
function profileKeyboard(id:string,profiles:string[]){const bs=profiles.slice(0,20).map((p,i)=>({text:p,callback_data:`ua:p:${id}:${i}`}));const rows:Array<Array<{text:string;callback_data:string}>>=[];for(let i=0;i<bs.length;i+=2)rows.push(bs.slice(i,i+2));rows.push([{text:"❌ إلغاء",callback_data:`ua:no:${id}`}]);return{inline_keyboard:rows};}
function passwordKeyboard(id:string){return{inline_keyboard:[[{text:"🔑 نفس اسم المستخدم",callback_data:`ua:same:${id}`}],[{text:"✍️ كلمة مرور جديدة",callback_data:`ua:custom:${id}`}],[{text:"❌ إلغاء",callback_data:`ua:no:${id}`}]]};}
function actionKeyboard(id:string,label="✅ تأكيد التنفيذ"){return{inline_keyboard:[[{text:label,callback_data:`ua:ok:${id}`}],[{text:"❌ إلغاء",callback_data:`ua:cancel:${id}`}]]};}
function deleteStage1Keyboard(id:string){return{inline_keyboard:[[{text:"⚠️ متابعة الحذف",callback_data:`ua:del1:${id}`}],[{text:"❌ إلغاء",callback_data:`ua:cancel:${id}`}]]};}
function deleteStage2Keyboard(id:string){return{inline_keyboard:[[{text:"🗑 نعم، احذف نهائيًا",callback_data:`ua:del2:${id}`}],[{text:"❌ تراجع",callback_data:`ua:cancel:${id}`}]]};}

async function cancelOpenSessions(uid:number){const rows=await dbGet<AdminSession>("tg_user_admin_sessions",{telegram_user_id:`eq.${uid}`,step:"in.(choose_profile,choose_password,await_password)",select:"*",order:"created_at.desc",limit:"20"});for(const s of rows)await dbPatch("tg_user_admin_sessions",{step:"cancelled",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});}

async function createPending(s:AdminSession,r:UserResolved,extra:Record<string,unknown>,actionType:string){const rows=await dbInsert<PendingAction>("tg_pending_actions",{telegram_user_id:s.telegram_user_id,chat_id:s.chat_id,network_id:s.network_id,action_type:actionType,target_type:"user",target_value:s.username,preview:{source:r.source,current_profile:currentProfile(r),active_sessions:r.active.length,currently_disabled:disabled(r.entry.disabled),...extra},status:"pending"},"*");const p=rows[0];if(!p)throw new Error("تعذر إنشاء طلب التأكيد");await audit({telegram_user_id:s.telegram_user_id,chat_id:s.chat_id,network_id:s.network_id,pending_action_id:p.id,action_type:actionType,target_value:s.username,phase:"preview",details:{source:r.source,current_profile:currentProfile(r),active_sessions:r.active.length,...Object.fromEntries(Object.entries(extra).filter(([k])=>k!=="password_ciphertext"))}});return p;}

async function start(update:TgUpdate,req:{operation:Operation;username:string;profile_hint?:string|null}){const m=update.message;if(!m?.from)return false;const n=await activeNetwork(m.from.id);if(!n){await send(m.chat.id,"📭 لا توجد شبكة نشطة.");return true;}if(n.connection_mode!=="direct"){await send(m.chat.id,"🔐 <b>إدارة المستخدمين الكتابية تحتاج Privileged Agent opt-in لهذه الشبكة.</b>\nلن أرفع صلاحيات Agent القراءة تلقائيًا.");return true;}const c=client(n);try{const r=await resolveUser(c,req.username);if(!r){await send(m.chat.id,`❌ لم أجد المستخدم <code>${esc(req.username)}</code> في Hotspot أو User Manager. لم أنفذ شيئًا.`);return true;}await cancelOpenSessions(m.from.id);
    const rows=await dbInsert<AdminSession>("tg_user_admin_sessions",{telegram_user_id:m.from.id,chat_id:m.chat.id,network_id:n.id,operation:req.operation,username:req.username,source:r.source,profiles:r.profiles,step:req.operation==="change_profile"?"choose_profile":req.operation==="change_password"?"choose_password":"delete_preview"},"*");const s=rows[0];if(!s)throw new Error("تعذر بدء جلسة الإدارة");
    if(req.operation==="change_profile"){
      if(!r.profiles.length){await send(m.chat.id,"⚠️ لم أجد Profiles متاحة على هذا النظام.");return true;}
      const hinted=req.profile_hint&&r.profiles.find(p=>normalizeLocalText(p)===normalizeLocalText(req.profile_hint!));
      if(hinted){await dbPatch("tg_user_admin_sessions",{selected_profile:hinted,step:"selected",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});const p=await createPending({...s,selected_profile:hinted},r,{new_profile:hinted},"change_user_profile");await send(m.chat.id,`🛡 <b>معاينة تغيير الباقة</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n👤 <code>${esc(req.username)}</code>\n📚 ${esc(sourceLabel(r.source))}\n🏷 الحالية: <b>${esc(currentProfile(r))}</b>\n➡️ الجديدة: <b>${esc(hinted)}</b>\n👥 جلسات نشطة: <b>${r.active.length}</b>\n\nلن أفصل الجلسة الحالية تلقائيًا.`,actionKeyboard(p.id,"✅ غيّر الباقة"));return true;}
      await send(m.chat.id,`🏷 <b>تغيير باقة المستخدم</b>\n━━━━━━━━━━━━━━━━━━\n👤 <code>${esc(req.username)}</code>\n📚 ${esc(sourceLabel(r.source))}\nالحالية: <b>${esc(currentProfile(r))}</b>\n\nاختر الباقة الجديدة:`,profileKeyboard(s.id,r.profiles));return true;
    }
    if(req.operation==="change_password"){await send(m.chat.id,`🔐 <b>تغيير كلمة المرور</b>\n━━━━━━━━━━━━━━━━━━\n👤 <code>${esc(req.username)}</code>\n📚 ${esc(sourceLabel(r.source))}\n\nاختر الطريقة:`,passwordKeyboard(s.id));return true;}
    const p=await createPending(s,r,{profile:currentProfile(r),disabled:disabled(r.entry.disabled),active_ips:r.active.map(x=>x.address).filter(Boolean).slice(0,8)},"delete_user");await send(m.chat.id,`🗑 <b>معاينة حذف المستخدم</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n👤 <code>${esc(req.username)}</code>\n📚 ${esc(sourceLabel(r.source))}\n🏷 الباقة: <b>${esc(currentProfile(r))}</b>\n🚦 الحالة: ${disabled(r.entry.disabled)?"⛔ معطل":"🟢 مفعّل"}\n👥 جلسات نشطة: <b>${r.active.length}</b>\n\n⚠️ الحذف نهائي من قاعدة المستخدمين. إذا أكملت سأطلب تأكيدًا ثانيًا قبل التنفيذ.`,deleteStage1Keyboard(p.id));return true;
  }catch(e){await send(m.chat.id,`🔴 تعذر تجهيز العملية.\n<code>${esc(e instanceof Error?e.message:e)}</code>`);return true;}finally{c.close();}}

async function latestAwaitingPassword(uid:number){return (await dbGet<AdminSession>("tg_user_admin_sessions",{telegram_user_id:`eq.${uid}`,operation:"eq.change_password",step:"eq.await_password",select:"*",order:"created_at.desc",limit:"1"}))[0]??null;}
async function passwordPreview(s:AdminSession,cipher:string){const n=await exactNetwork(s.telegram_user_id,s.network_id);if(!n)throw new Error("الشبكة لم تعد موجودة");const c=client(n);try{const r=await resolveUser(c,s.username);if(!r)throw new Error("المستخدم لم يعد موجودًا");await dbPatch("tg_user_admin_sessions",{password_ciphertext:cipher,step:"selected",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});const p=await createPending({...s,password_ciphertext:cipher},r,{password_ciphertext:cipher},"change_user_password");await send(s.chat_id,`🛡 <b>معاينة تغيير كلمة المرور</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n👤 <code>${esc(s.username)}</code>\n📚 ${esc(sourceLabel(r.source))}\n🔑 كلمة المرور الجديدة: <b>محفوظة ومخفية</b>\n👥 جلسات نشطة: <b>${r.active.length}</b>\n\nلن أفصل الجلسة الحالية تلقائيًا.`,actionKeyboard(p.id,"✅ غيّر كلمة المرور"));}finally{c.close();}}

async function executeProfile(c:RouterOSClient,r:UserResolved,username:string,newProfile:string){if(!r.profiles.includes(newProfile))throw new Error("الباقة المطلوبة لم تعد موجودة على الراوتر");if(r.source==="hotspot"){await c.command("/ip/hotspot/user/set",[`=.id=${r.entry[".id"]}`,`=profile=${newProfile}`]);return;}
  if(r.source==="user-manager-v6"){await c.command("/tool/user-manager/user/create-and-activate-profile",[`=customer=${r.customer||"admin"}`,`=numbers=${username}`,`=profile=${newProfile}`]);return;}
  await c.command("/user-manager/user-profile/add",[`=user=${username}`,`=profile=${newProfile}`]);let row:Record<string,string>|undefined;try{const rows=await c.command("/user-manager/user-profile/print",["=.proplist=.id,user,profile,state",`?user=${username}`,`?profile=${newProfile}`]);row=rows.at(-1);}catch{}
  if(row?.[".id"]){try{await c.command("/user-manager/user-profile/activate-user-profile",[`=.id=${row[".id"]}`]);}catch(e){try{await c.command("/user-manager/user-profile/remove",[`=.id=${row[".id"]}`]);}catch{}throw new Error(`تعيين الباقة أُنشئ لكن تفعيلها فشل وتم التراجع: ${e instanceof Error?e.message:e}`);}}
}
async function executePassword(c:RouterOSClient,r:UserResolved,newPassword:string){const path=r.source==="hotspot"?"/ip/hotspot/user/set":r.source==="user-manager-v6"?"/tool/user-manager/user/set":"/user-manager/user/set";await c.command(path,[`=.id=${r.entry[".id"]}`,`=password=${newPassword}`]);}
async function executeDelete(c:RouterOSClient,r:UserResolved){for(const a of r.active){if(a[".id"])try{await c.command("/ip/hotspot/active/remove",[`=.id=${a[".id"]}`]);}catch{}}
  const path=r.source==="hotspot"?"/ip/hotspot/user/remove":r.source==="user-manager-v6"?"/tool/user-manager/user/remove":"/user-manager/user/remove";await c.command(path,[`=.id=${r.entry[".id"]}`]);}

async function executePending(p:PendingAction,cbId:string,chatId:number,messageId?:number){const n=await exactNetwork(p.telegram_user_id,p.network_id);if(!n)throw new Error("الشبكة لم تعد موجودة");const c=client(n);try{const r=await resolveUser(c,p.target_value);if(!r)throw new Error("المستخدم لم يعد موجودًا؛ لم أنفذ شيئًا");if(String(p.preview.source||"")!==r.source)throw new Error("مصدر المستخدم تغيّر منذ المعاينة؛ أعد الطلب من جديد");await dbPatch("tg_pending_actions",{status:"running",confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{id:`eq.${p.id}`,status:"eq.pending"});await audit({telegram_user_id:p.telegram_user_id,chat_id:p.chat_id,network_id:p.network_id,pending_action_id:p.id,action_type:p.action_type,target_value:p.target_value,phase:"confirmed",details:{source:r.source}});
    if(p.action_type==="change_user_profile"){const np=String(p.preview.new_profile||"");if(!np)throw new Error("الباقة الجديدة مفقودة");await executeProfile(c,r,p.target_value,np);}
    else if(p.action_type==="change_user_password"){const cipher=String(p.preview.password_ciphertext||"");if(!cipher)throw new Error("كلمة المرور المشفرة مفقودة");await executePassword(c,r,decryptSecret(cipher));}
    else if(p.action_type==="delete_user")await executeDelete(c,r);else throw new Error("نوع العملية غير مدعوم");
    await dbPatch("tg_pending_actions",{status:"completed",completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{id:`eq.${p.id}`});await audit({telegram_user_id:p.telegram_user_id,chat_id:p.chat_id,network_id:p.network_id,pending_action_id:p.id,action_type:p.action_type,target_value:p.target_value,phase:"success",details:{source:r.source,new_profile:p.preview.new_profile||null,disconnected_sessions:p.action_type==="delete_user"?r.active.length:0}});await answer(cbId,"تم التنفيذ");const label=p.action_type==="change_user_profile"?`✅ تم تغيير باقة <code>${esc(p.target_value)}</code> إلى <b>${esc(p.preview.new_profile)}</b>.`:p.action_type==="change_user_password"?`✅ تم تغيير كلمة مرور <code>${esc(p.target_value)}</code> بنجاح.`:`✅ تم حذف المستخدم <code>${esc(p.target_value)}</code> نهائيًا${r.active.length?` وفصل ${r.active.length} جلسة نشطة`:""}.`;if(messageId)await edit(chatId,messageId,label);else await send(chatId,label);return true;
  }catch(e){const msg=e instanceof Error?e.message:String(e);await dbPatch("tg_pending_actions",{status:"error",error_text:msg.slice(0,500),updated_at:new Date().toISOString()},{id:`eq.${p.id}`});await audit({telegram_user_id:p.telegram_user_id,chat_id:p.chat_id,network_id:p.network_id,pending_action_id:p.id,action_type:p.action_type,target_value:p.target_value,phase:"error",details:{error:msg.slice(0,500)}});await answer(cbId,"فشل التنفيذ",true);if(messageId)await edit(chatId,messageId,`🔴 <b>لم تكتمل العملية</b>\n<code>${esc(msg)}</code>`);else await send(chatId,`🔴 لم تكتمل العملية: <code>${esc(msg)}</code>`);return true;}finally{c.close();}}

async function callback(update:TgUpdate){const cb=update.callback_query;if(!cb?.data||!/^ua:/i.test(cb.data))return false;const parts=cb.data.split(":");const kind=parts[1];const id=parts[2];const extra=parts[3];const chatId=cb.message?.chat.id??cb.from.id;const messageId=cb.message?.message_id;
  if(kind==="p"||kind==="same"||kind==="custom"||kind==="no"){
    const s=(await dbGet<AdminSession>("tg_user_admin_sessions",{id:`eq.${id}`,telegram_user_id:`eq.${cb.from.id}`,select:"*",limit:"1"}))[0];if(!s){await answer(cb.id,"الجلسة غير موجودة",true);return true;}if(new Date(s.expires_at).getTime()<Date.now()){await dbPatch("tg_user_admin_sessions",{step:"expired",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"انتهت الجلسة",true);if(messageId)await edit(chatId,messageId,"⌛ انتهت الجلسة. أرسل الطلب من جديد.");return true;}if(kind==="no"){await dbPatch("tg_user_admin_sessions",{step:"cancelled",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"تم الإلغاء");if(messageId)await edit(chatId,messageId,"❌ تم الإلغاء. لم أغيّر شيئًا.");return true;}
    if(kind==="p"){const idx=Number(extra);const prof=s.profiles[idx];if(!prof){await answer(cb.id,"الباقة غير موجودة",true);return true;}const n=await exactNetwork(s.telegram_user_id,s.network_id);if(!n){await answer(cb.id,"الشبكة غير موجودة",true);return true;}const c=client(n);try{const r=await resolveUser(c,s.username);if(!r){await answer(cb.id,"المستخدم غير موجود",true);return true;}await dbPatch("tg_user_admin_sessions",{selected_profile:prof,step:"selected",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});const p=await createPending({...s,selected_profile:prof},r,{new_profile:prof},"change_user_profile");await answer(cb.id,"تم اختيار الباقة");if(messageId)await edit(chatId,messageId,`🛡 <b>معاينة تغيير الباقة</b>\n━━━━━━━━━━━━━━━━━━\n👤 <code>${esc(s.username)}</code>\n🏷 الحالية: <b>${esc(currentProfile(r))}</b>\n➡️ الجديدة: <b>${esc(prof)}</b>\n👥 جلسات نشطة: <b>${r.active.length}</b>`,actionKeyboard(p.id,"✅ غيّر الباقة"));return true;}finally{c.close();}}
    if(kind==="same"){await answer(cb.id,"سيتم استخدام اسم المستخدم");await passwordPreview(s,encryptSecret(s.username));if(messageId)await edit(chatId,messageId,"🔑 تم اختيار كلمة مرور مطابقة لاسم المستخدم. أرسلت لك معاينة التأكيد في رسالة جديدة.");return true;}
    await dbPatch("tg_user_admin_sessions",{step:"await_password",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"أرسل كلمة المرور");if(messageId)await edit(chatId,messageId,`✍️ أرسل الآن كلمة المرور الجديدة للمستخدم <code>${esc(s.username)}</code>.\nسأحذف رسالتك من Telegram فور استلامها ولن أسجلها كنص.`);return true;
  }
  const p=(await dbGet<PendingAction>("tg_pending_actions",{id:`eq.${id}`,telegram_user_id:`eq.${cb.from.id}`,select:"*",limit:"1"}))[0];if(!p){await answer(cb.id,"طلب التأكيد غير موجود",true);return true;}if(p.status!=="pending"){await answer(cb.id,"هذا الطلب لم يعد نشطًا",true);return true;}if(new Date(p.expires_at).getTime()<Date.now()){await dbPatch("tg_pending_actions",{status:"expired",updated_at:new Date().toISOString()},{id:`eq.${p.id}`});await answer(cb.id,"انتهت صلاحية الطلب",true);if(messageId)await edit(chatId,messageId,"⌛ انتهت صلاحية التأكيد. أرسل الطلب من جديد.");return true;}
  if(kind==="cancel"){await dbPatch("tg_pending_actions",{status:"cancelled",updated_at:new Date().toISOString()},{id:`eq.${p.id}`});await audit({telegram_user_id:p.telegram_user_id,chat_id:p.chat_id,network_id:p.network_id,pending_action_id:p.id,action_type:p.action_type,target_value:p.target_value,phase:"cancelled"});await answer(cb.id,"تم الإلغاء");if(messageId)await edit(chatId,messageId,"❌ تم الإلغاء. لم أغيّر شيئًا.");return true;}
  if(kind==="del1"&&p.action_type==="delete_user"){await answer(cb.id,"تأكيد أخير");if(messageId)await edit(chatId,messageId,`🚨 <b>التأكيد النهائي للحذف</b>\n━━━━━━━━━━━━━━━━━━\n👤 <code>${esc(p.target_value)}</code>\n\nسيُحذف الحساب من ${esc(p.preview.source)}، وستُفصل جلساته النشطة إن وجدت.\n<b>هذا الإجراء غير قابل للتراجع من البوت.</b>`,deleteStage2Keyboard(p.id));return true;}
  if(kind==="del2"&&p.action_type==="delete_user")return executePending(p,cb.id,chatId,messageId);
  if(kind==="ok"&&p.action_type!=="delete_user")return executePending(p,cb.id,chatId,messageId);
  await answer(cb.id,"تأكيد غير صالح",true);return true;
}

async function awaitingPassword(update:TgUpdate){const m=update.message;if(!m?.from||!m.text||m.text.startsWith("/"))return false;const s=await latestAwaitingPassword(m.from.id);if(!s)return false;if(new Date(s.expires_at).getTime()<Date.now()){await dbPatch("tg_user_admin_sessions",{step:"expired",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});return false;}const raw=m.text;await del(m.chat.id,m.message_id);if(raw.length<1||raw.length>128){await send(m.chat.id,"⚠️ كلمة المرور يجب أن تكون بين 1 و128 حرفًا. أرسلها مرة أخرى.");return true;}await passwordPreview(s,encryptSecret(raw));return true;}

function userHelp(){return `👤 <b>إدارة المستخدم</b>\n━━━━━━━━━━━━━━━━━━\nيمكنك الكلام طبيعيًا:\n• غير باقة المستخدم <code>773032</code> إلى <code>500</code>\n• غير كلمة مرور الكرت <code>AB-12_X</code>\n• احذف المستخدم <code>test-user</code>\n• افحص المستخدم <code>773032</code>\n\nأوامر اختيارية:\n<code>/user USER</code> — تقرير\n<code>/user profile USER</code> — تغيير الباقة\n<code>/user password USER</code> — تغيير كلمة المرور\n<code>/user delete USER</code> — حذف آمن بتأكيدين\n\nتعطيل/تفعيل وفصل الجلسة يعمل أيضًا بالكلام الطبيعي مع زر تأكيد.`;}

export async function handleTelegramUserAdmin(update:TgUpdate):Promise<boolean>{if(await callback(update))return true;if(await awaitingPassword(update))return true;const m=update.message;if(!m?.from||!m.text)return false;const raw=m.text.trim();if(!raw)return false;
  if(/^\/user(?:@\w+)?$/i.test(raw)){await send(m.chat.id,userHelp());return true;}
  const userInfo=raw.match(/^\/user(?:@\w+)?\s+(?:info\s+)?([^\s]+)$/i);if(userInfo){return handleTelegramCardUniversal({...update,message:{...m,text:`/card ${userInfo[1]}`}});}
  const req=parseRequest(raw);if(!req)return false;return start(update,req);
}
