import { dbGet, dbInsert, dbPatch } from "./telegram-db";

type Rule={id:string;telegram_user_id:number;network_id:string;kind:string;target?:string|null;enabled:boolean;consecutive_failures:number;consecutive_recoveries:number};
type Network={id:string;telegram_user_id:number;label:string;identity?:string|null;connection_mode:string};
type State={rule_id:string;current_state:string;bad_count:number;good_count:number;last_value:Record<string,unknown>;active_since?:string|null;last_checked_at?:string|null;last_notified_at?:string|null};
type Cmd={id:string;kind:string;status:string;result?:Record<string,string>|null;created_at:string;completed_at?:string|null};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function send(chatId:number,text:string){const r=await fetch(`https://api.telegram.org/bot${token()}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true}),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);}
function duration(ms:number){const min=Math.max(1,Math.round(ms/60000));if(min<60)return`${min} دقيقة`;const h=Math.floor(min/60),m=min%60;return m?`${h} ساعة و${m} دقيقة`:`${h} ساعة`;}

async function latest(networkId:string,kind:string){return(await dbGet<Cmd>("tg_agent_commands",{network_id:`eq.${networkId}`,kind:`eq.${kind}`,chat_id:"eq.0",status:"eq.success",select:"id,kind,status,result,created_at,completed_at",order:"completed_at.desc",limit:"1"}))[0]??null;}
async function ensureTelemetry(n:Network,kind:"interfaces"|"vlans",last:Cmd|null){const at=last?.completed_at||last?.created_at;const fresh=Boolean(at&&Date.now()-new Date(at).getTime()<60_000);if(fresh)return true;const pending=await dbGet<{id:string}>("tg_agent_commands",{network_id:`eq.${n.id}`,kind:`eq.${kind}`,chat_id:"eq.0",status:"in.(pending,claimed)",select:"id",limit:"1"});if(!pending.length){await dbInsert("tg_agent_commands",{network_id:n.id,telegram_user_id:n.telegram_user_id,chat_id:0,reply_message_id:null,kind,payload:{telemetry:true,target_alerts:true},status:"pending"});}return false;}
function parseInterfaces(d:Record<string,string>|null|undefined){const out=new Map<string,{running:boolean;disabled:boolean;type:string}>();for(const row of (d?.items||"").split(";").filter(Boolean)){const [name,type,running,disabled]=row.split("@");if(name)out.set(name,{type:type||"",running:running==="1",disabled:disabled==="1"});}return out;}
function parseVlans(d:Record<string,string>|null|undefined){const out=new Map<number,string>();for(const row of (d?.items||"").split(";").filter(Boolean)){const [id,name]=row.split("@");const n=Number(id);if(Number.isInteger(n)&&n>0)out.set(n,name||`VLAN ${n}`);}return out;}
async function state(id:string){return(await dbGet<State>("tg_alert_state",{rule_id:`eq.${id}`,select:"*",limit:"1"}))[0]??null;}
async function save(id:string,old:State|null,patch:Record<string,unknown>){const body={...patch,updated_at:new Date().toISOString()};if(old)await dbPatch("tg_alert_state",body,{rule_id:`eq.${id}`});else await dbInsert("tg_alert_state",{rule_id:id,current_state:"unknown",bad_count:0,good_count:0,last_value:{},...body});}

async function transition(rule:Rule,n:Network,bad:boolean,title:string,detail:string,recovery:string,value:Record<string,unknown>){const now=new Date(),old=await state(rule.id),was=old?.current_state==="alert";if(bad){const count=(old?.bad_count||0)+1,fire=!was&&count>=Math.max(1,rule.consecutive_failures||1);if(fire)await send(rule.telegram_user_id,`🔴 <b>${esc(n.identity||n.label)} • تنبيه</b>\n━━━━━━━━━━━━━━━━━━\n⚠️ <b>${esc(title)}</b>\n${esc(detail)}\n\n✅ تم التأكيد بعد <b>${Math.max(1,rule.consecutive_failures||1)}</b> فحوص متتالية عبر Agent.`);await save(rule.id,old,{current_state:fire||was?"alert":(old?.current_state||"unknown"),bad_count:count,good_count:0,last_value:value,active_since:was?(old?.active_since||now.toISOString()):(fire?now.toISOString():old?.active_since||null),last_checked_at:now.toISOString(),last_notified_at:fire?now.toISOString():old?.last_notified_at||null,last_error:null});return;}
 const good=(old?.good_count||0)+1,recover=was&&good>=Math.max(1,rule.consecutive_recoveries||1);if(recover){const since=old?.active_since?new Date(old.active_since).getTime():now.getTime();await send(rule.telegram_user_id,`🟢 <b>${esc(n.identity||n.label)} • عادت طبيعية</b>\n━━━━━━━━━━━━━━━━━━\n✅ ${esc(recovery)}\n⏱ مدة الحالة تقريبًا: <b>${esc(duration(now.getTime()-since))}</b>.`);}await save(rule.id,old,{current_state:recover||!was?"normal":"alert",bad_count:0,good_count:good,last_value:value,active_since:recover?null:old?.active_since||null,last_checked_at:now.toISOString(),last_notified_at:recover?now.toISOString():old?.last_notified_at||null,last_error:null});}

export async function runAgentTargetAlertChecks(){const rules=await dbGet<Rule>("tg_alert_rules",{enabled:"eq.true",kind:"eq.interface_down",select:"id,telegram_user_id,network_id,kind,target,enabled,consecutive_failures,consecutive_recoveries",limit:"200"});if(!rules.length)return[];const ids=[...new Set(rules.map(x=>x.network_id))];const results:Array<{network_id:string;checked:number;waiting:boolean}>=[];
 for(const networkId of ids){const n=(await dbGet<Network>("tg_networks",{id:`eq.${networkId}`,connection_mode:"eq.agent",select:"id,telegram_user_id,label,identity,connection_mode",limit:"1"}))[0];if(!n)continue;const group=rules.filter(x=>x.network_id===networkId&&x.target);const needsVlan=group.some(x=>String(x.target).startsWith("vlan:")),needsInterface=group.some(x=>!String(x.target).startsWith("vlan:"));let intCmd:Cmd|null=null,vlanCmd:Cmd|null=null,intReady=!needsInterface,vlanReady=!needsVlan;if(needsInterface){intCmd=await latest(n.id,"interfaces");intReady=await ensureTelemetry(n,"interfaces",intCmd);}if(needsVlan){vlanCmd=await latest(n.id,"vlans");vlanReady=await ensureTelemetry(n,"vlans",vlanCmd);}if(!intReady||!vlanReady){results.push({network_id:n.id,checked:0,waiting:true});continue;}const interfaces=parseInterfaces(intCmd?.result),vlans=parseVlans(vlanCmd?.result);let checked=0;
  for(const rule of group){const target=String(rule.target||"");if(target.startsWith("vlan:")){const id=Number(target.slice(5)),name=vlans.get(id),bad=!name;await transition(rule,n,bad,bad?`VLAN ${id} متوقف أو غير ظاهر`:`VLAN ${id}`,bad?`Agent لم يجد VLAN ${id} ضمن VLANs المفعلة.`:`${name} ظاهر ضمن VLANs المفعلة.`,`VLAN ${id} عاد للظهور ضمن VLANs المفعلة.`,{target,found:Boolean(name),name:name||null,source:"agent-vlans"});checked++;continue;}const x=interfaces.get(target),bad=!x||x.disabled||!x.running;await transition(rule,n,bad,!x?`Interface ${target} غير موجود`:`Interface ${target} متوقف`,!x?`Agent لم يجد Interface باسم ${target}.`:`running=${x.running?"yes":"no"}, disabled=${x.disabled?"yes":"no"}.`,`Interface ${target} عاد Running.`,{target,found:Boolean(x),running:x?.running??false,disabled:x?.disabled??false,type:x?.type||null,source:"agent-interfaces"});checked++;}
  results.push({network_id:n.id,checked,waiting:false});
 }
 return results;}
