import { decryptSecret, encryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert, dbPatch } from "./telegram-db";
import { RouterOSClient } from "./routeros-api";
import type { TgUpdate } from "./telegram-extra";

type Network={id:string;telegram_user_id:number;label:string;connection_mode:"direct"|"agent";host?:string|null;port?:number|null;username?:string|null;password_ciphertext?:string|null;protocol:"api"|"api-ssl";tls_verify:boolean;identity?:string|null;router_os_version?:string|null};
type BotUser={telegram_user_id:number;active_network_id?:string|null};
type Source="user-manager-v6"|"user-manager-v7"|"hotspot";
type Session={id:string;telegram_user_id:number;chat_id:number;network_id:string;username:string;source:Source;customer?:string|null;profiles:string[];selected_profile?:string|null;password_ciphertext?:string|null;step:string;expires_at:string;created_at:string};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function tg(method:string,payload:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
function send(chatId:number,text:string,reply_markup?:unknown){return tg("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}
async function edit(chatId:number,messageId:number,text:string,reply_markup?:unknown){try{return await tg("editMessageText",{chat_id:chatId,message_id:messageId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}catch{return null;}}
async function answer(id:string,text?:string){try{await tg("answerCallbackQuery",{callback_query_id:id,text});}catch{}}
async function del(chatId:number,messageId:number){try{await tg("deleteMessage",{chat_id:chatId,message_id:messageId});}catch{}}
function client(n:Network){if(n.connection_mode!=="direct"||!n.host||!n.port||!n.username||!n.password_ciphertext)throw new Error("إنشاء المستخدمين يحتاج Direct API حاليًا؛ Agent privileged سيأخذ نفس الوظيفة لاحقًا.");return new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:22000});}
async function activeNetwork(uid:number){const u=(await dbGet<BotUser>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id",limit:"1"}))[0];if(!u?.active_network_id)return null;return (await dbGet<Network>("tg_networks",{id:`eq.${u.active_network_id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}
async function exactNetwork(uid:number,id:string){return (await dbGet<Network>("tg_networks",{id:`eq.${id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}
async function audit(s:Session,phase:string,details:Record<string,unknown>={}){await dbInsert("tg_action_audit",{telegram_user_id:s.telegram_user_id,chat_id:s.chat_id,network_id:s.network_id,pending_action_id:null,action_type:"add_user",target_type:"user",target_value:s.username,phase,details});}

function usernameFrom(raw:string){const quoted=raw.match(/["'«]([^"'»]{2,128})["'»]/u)?.[1]?.trim();if(quoted&&/^[\p{L}\p{N}_.@:+-]{2,128}$/u.test(quoted))return quoted;const m=raw.match(/(?:اضف|أضف|انشئ|أنشئ|سوي|اعمل|create|add)\s*(?:لي\s*)?(?:مستخدم|يوزر|كرت|user|card)\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{2,128})/iu)?.[1];return m||null;}
function isAddUserRequest(raw:string){return /(?:اضف|أضف|انشئ|أنشئ|سوي|اعمل|create|add)\s*(?:لي\s*)?(?:مستخدم|يوزر|كرت|user|card)(?:\s|$)/iu.test(raw.trim());}
function profileKeyboard(sessionId:string,profiles:string[]){const buttons=profiles.slice(0,12).map((p,i)=>({text:p,callback_data:`uc:p:${sessionId}:${i}`}));const rows=[] as Array<Array<{text:string;callback_data:string}>>;for(let i=0;i<buttons.length;i+=2)rows.push(buttons.slice(i,i+2));rows.push([{text:"❌ إلغاء",callback_data:`uc:no:${sessionId}`}]);return{inline_keyboard:rows};}
function passwordKeyboard(id:string){return{inline_keyboard:[[{text:"🔑 نفس اسم المستخدم",callback_data:`uc:same:${id}`}],[{text:"✍️ كلمة مرور مختلفة",callback_data:`uc:custom:${id}`}],[{text:"❌ إلغاء",callback_data:`uc:no:${id}`}]]};}
function confirmKeyboard(id:string){return{inline_keyboard:[[{text:"✅ إنشاء المستخدم",callback_data:`uc:ok:${id}`}],[{text:"❌ إلغاء",callback_data:`uc:no:${id}`}]]};}

async function detect(c:RouterOSClient){const res=await c.command("/system/resource/print",["=.proplist=version"]);const version=res[0]?.version||"";const major=Number(/^\d+/.exec(version)?.[0]||0);
  if(major>=7){try{const rows=await c.command("/user-manager/profile/print",["=.proplist=name"]);const profiles=rows.map(x=>x.name).filter(Boolean);if(profiles.length)return{source:"user-manager-v7" as Source,profiles,customer:null,version};}catch{}}
  else{try{const rows=await c.command("/tool/user-manager/profile/print",["=.proplist=name"]);const profiles=rows.map(x=>x.name).filter(Boolean);if(profiles.length){let customer="admin";try{const cs=await c.command("/tool/user-manager/customer/print");const first=cs[0]||{};customer=first.login||first.name||first.username||"admin";}catch{}return{source:"user-manager-v6" as Source,profiles,customer,version};}}catch{}}
  const hp=await c.command("/ip/hotspot/user/profile/print",["=.proplist=name"]);const profiles=hp.map(x=>x.name).filter(Boolean);if(profiles.length)return{source:"hotspot" as Source,profiles,customer:null,version};throw new Error("لم أجد User Manager profiles ولا Hotspot user profiles على الراوتر.");}

async function existing(c:RouterOSClient,s:Session){if(s.source==="user-manager-v6")return (await c.command("/tool/user-manager/user/print",["=.proplist=.id,username",`?username=${s.username}`]))[0]||null;if(s.source==="user-manager-v7")return (await c.command("/user-manager/user/print",["=.proplist=.id,name",`?name=${s.username}`]))[0]||null;return (await c.command("/ip/hotspot/user/print",["=.proplist=.id,name",`?name=${s.username}`]))[0]||null;}
async function rollback(c:RouterOSClient,s:Session){try{const row=await existing(c,s);const id=row?.[".id"];if(!id)return true;if(s.source==="user-manager-v6")await c.command("/tool/user-manager/user/remove",[`=.id=${id}`]);else if(s.source==="user-manager-v7")await c.command("/user-manager/user/remove",[`=.id=${id}`]);else await c.command("/ip/hotspot/user/remove",[`=.id=${id}`]);return true;}catch{return false;}}
async function createOnRouter(s:Session,n:Network){if(!s.selected_profile||!s.password_ciphertext)throw new Error("بيانات الإنشاء غير مكتملة");const password=decryptSecret(s.password_ciphertext);const c=client(n);let created=false;try{if(await existing(c,s))throw new Error("المستخدم موجود أصلًا على الراوتر");if(s.source==="hotspot"){await c.command("/ip/hotspot/user/add",[`=name=${s.username}`,`=password=${password}`,`=profile=${s.selected_profile}`,"=disabled=no"]);created=true;return{source:s.source,profile:s.selected_profile,rollback:false};}
    if(s.source==="user-manager-v6"){const customer=s.customer||"admin";await c.command("/tool/user-manager/user/add",[`=customer=${customer}`,`=username=${s.username}`,`=password=${password}`,"=shared-users=1","=disabled=no"]);created=true;try{await c.command("/tool/user-manager/user/create-and-activate-profile",[`=customer=${customer}`,`=numbers=${s.username}`,`=profile=${s.selected_profile}`]);}catch(e){const rb=await rollback(c,s);throw new Error(`تم إنشاء المستخدم لكن تعيين الباقة فشل؛ ${rb?"تم التراجع وحذف المستخدم الجديد بنجاح":"تعذر التراجع تلقائيًا ويحتاج مراجعة"}. السبب: ${e instanceof Error?e.message:e}`);}return{source:s.source,profile:s.selected_profile,rollback:false};}
    await c.command("/user-manager/user/add",[`=name=${s.username}`,`=password=${password}`,"=shared-users=1","=disabled=no"]);created=true;try{await c.command("/user-manager/user-profile/add",[`=user=${s.username}`,`=profile=${s.selected_profile}`]);}catch(e){const rb=await rollback(c,s);throw new Error(`تم إنشاء المستخدم لكن تعيين الباقة فشل؛ ${rb?"تم التراجع وحذف المستخدم الجديد بنجاح":"تعذر التراجع تلقائيًا ويحتاج مراجعة"}. السبب: ${e instanceof Error?e.message:e}`);}return{source:s.source,profile:s.selected_profile,rollback:false};
  }catch(e){if(created&&!(e instanceof Error&&e.message.includes("تم إنشاء المستخدم لكن")))await rollback(c,s);throw e;}finally{c.close();}}

async function start(update:TgUpdate,username:string){const m=update.message;if(!m?.from)return false;const n=await activeNetwork(m.from.id);if(!n){await send(m.chat.id,"📭 لا توجد شبكة نشطة. أضف/اختر شبكة أولًا.");return true;}if(n.connection_mode!=="direct"){await send(m.chat.id,"🔐 إنشاء المستخدمين على Agent يحتاج Privileged Agent opt-in. لن أرفع الصلاحيات تلقائيًا.");return true;}const c=client(n);try{const d=await detect(c);const old=await dbGet<Session>("tg_user_create_sessions",{telegram_user_id:`eq.${m.from.id}`,step:"in.(choose_profile,choose_password,await_password,confirm)",select:"*",order:"created_at.desc",limit:"20"});for(const x of old)await dbPatch("tg_user_create_sessions",{step:"cancelled",updated_at:new Date().toISOString()},{id:`eq.${x.id}`});const rows=await dbInsert<Session>("tg_user_create_sessions",{telegram_user_id:m.from.id,chat_id:m.chat.id,network_id:n.id,username,source:d.source,customer:d.customer,profiles:d.profiles.slice(0,50),step:"choose_profile"},"*");const s=rows[0];if(!s)throw new Error("تعذر بدء جلسة إنشاء المستخدم");await audit(s,"preview",{stage:"choose_profile",source:d.source,profiles:d.profiles.length});await send(m.chat.id,`➕ <b>إضافة مستخدم جديد</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n👤 Username: <code>${esc(username)}</code>\n📚 المصدر: <b>${esc(d.source)}</b>\n🧩 RouterOS: ${esc(d.version)}\n\nاختر الباقة/البروفايل:`,profileKeyboard(s.id,d.profiles));return true;}catch(e){await send(m.chat.id,`🔴 تعذر بدء إضافة المستخدم.\n<code>${esc(e instanceof Error?e.message:e)}</code>`);return true;}finally{c.close();}}

async function latestAwaitingPassword(uid:number){return (await dbGet<Session>("tg_user_create_sessions",{telegram_user_id:`eq.${uid}`,step:"eq.await_password",select:"*",order:"created_at.desc",limit:"1"}))[0]??null;}
async function showConfirm(s:Session,chatId:number,messageId?:number){const n=await exactNetwork(s.telegram_user_id,s.network_id);const text=`🛡 <b>تأكيد إنشاء المستخدم</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n?.identity||n?.label||"MikroTik")}\n👤 Username: <code>${esc(s.username)}</code>\n🏷 Profile: <b>${esc(s.selected_profile||"-")}</b>\n📚 المصدر: ${esc(s.source)}\n🔑 كلمة المرور: <b>محفوظة ومخفية</b>\n\nلن أرسل كلمة المرور في السجل أو أعرضها مرة أخرى.`;if(messageId)await edit(chatId,messageId,text,confirmKeyboard(s.id));else await send(chatId,text,confirmKeyboard(s.id));}

async function callback(update:TgUpdate){const cb=update.callback_query;if(!cb?.data||!/^uc:(?:p|same|custom|ok|no):/i.test(cb.data))return false;const parts=cb.data.split(":");const kind=parts[1];const id=parts[2];const chatId=cb.message?.chat.id??cb.from.id;const messageId=cb.message?.message_id;const s=(await dbGet<Session>("tg_user_create_sessions",{id:`eq.${id}`,telegram_user_id:`eq.${cb.from.id}`,select:"*",limit:"1"}))[0];if(!s){await answer(cb.id,"الجلسة غير موجودة");return true;}if(new Date(s.expires_at).getTime()<Date.now()){await dbPatch("tg_user_create_sessions",{step:"expired",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"انتهت صلاحية الجلسة");if(messageId)await edit(chatId,messageId,"⌛ انتهت جلسة إضافة المستخدم. أرسل الطلب من جديد.");return true;}if(kind==="no"){await dbPatch("tg_user_create_sessions",{step:"cancelled",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await audit(s,"cancelled");await answer(cb.id,"تم الإلغاء");if(messageId)await edit(chatId,messageId,"❌ تم إلغاء إضافة المستخدم. لم أغيّر شيئًا في الراوتر.");return true;}
  if(kind==="p"){if(s.step!=="choose_profile"){await answer(cb.id,"هذه الخطوة انتهت");return true;}const index=Number(parts[3]);const profile=s.profiles[index];if(!profile){await answer(cb.id,"الباقة غير موجودة");return true;}await dbPatch("tg_user_create_sessions",{selected_profile:profile,step:"choose_password",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"تم اختيار الباقة");if(messageId)await edit(chatId,messageId,`🔑 <b>كلمة مرور المستخدم</b>\n👤 <code>${esc(s.username)}</code>\n🏷 ${esc(profile)}\n\nاختر كيف تريد كلمة المرور:`,passwordKeyboard(s.id));return true;}
  if(kind==="same"){if(s.step!=="choose_password"){await answer(cb.id,"هذه الخطوة انتهت");return true;}await dbPatch("tg_user_create_sessions",{password_ciphertext:encryptSecret(s.username),step:"confirm",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});const fresh={...s,password_ciphertext:"stored",step:"confirm"};await answer(cb.id,"تم");await showConfirm(fresh,chatId,messageId);return true;}
  if(kind==="custom"){if(s.step!=="choose_password"){await answer(cb.id,"هذه الخطوة انتهت");return true;}await dbPatch("tg_user_create_sessions",{step:"await_password",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"أرسل كلمة المرور");if(messageId)await edit(chatId,messageId,`🔐 <b>أرسل كلمة المرور الجديدة الآن برسالة واحدة.</b>\nسأحذف رسالتك من Telegram مباشرة بعد قراءتها ولن أسجل النص.`);return true;}
  if(kind==="ok"){if(s.step!=="confirm"){await answer(cb.id,"هذه الخطوة انتهت");return true;}const n=await exactNetwork(s.telegram_user_id,s.network_id);if(!n){await answer(cb.id,"الشبكة غير موجودة");return true;}await answer(cb.id,"جاري الإنشاء…");await dbPatch("tg_user_create_sessions",{step:"executing",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await audit(s,"confirmed",{profile:s.selected_profile,source:s.source});await audit(s,"executing",{profile:s.selected_profile,source:s.source});if(messageId)await edit(chatId,messageId,`⏳ <b>جاري إنشاء المستخدم…</b>\n<code>${esc(s.username)}</code> • ${esc(s.selected_profile||"-")}`);try{const result=await createOnRouter(s,n);await dbPatch("tg_user_create_sessions",{step:"completed",updated_at:new Date().toISOString(),error_text:null},{id:`eq.${s.id}`});await audit(s,"success",result);const text=`✅ <b>تم إنشاء المستخدم بنجاح</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n👤 <code>${esc(s.username)}</code>\n🏷 ${esc(s.selected_profile||"-")}\n📚 ${esc(s.source)}\n\n🔑 كلمة المرور لم تُعرض أو تُسجل.\n🧾 العملية مسجلة في Audit Log.`;if(messageId)await edit(chatId,messageId,text);else await send(chatId,text);}catch(e){const error=e instanceof Error?e.message:String(e);await dbPatch("tg_user_create_sessions",{step:"error",updated_at:new Date().toISOString(),error_text:error.slice(0,1000)},{id:`eq.${s.id}`});await audit(s,"error",{error:error.slice(0,1000)});const text=`🔴 <b>فشل إنشاء المستخدم</b>\n<code>${esc(error)}</code>\n\nإذا كان الإنشاء الجزئي حصل، حاولت التراجع تلقائيًا كما هو موضح في الخطأ.`;if(messageId)await edit(chatId,messageId,text);else await send(chatId,text);}return true;}return false;}

async function passwordMessage(update:TgUpdate){const m=update.message;if(!m?.text||!m.from)return false;const s=await latestAwaitingPassword(m.from.id);if(!s)return false;const raw=m.text.trim();if(!raw)return true;await del(m.chat.id,m.message_id);if(raw.length<1||raw.length>128){await send(m.chat.id,"❌ كلمة المرور يجب أن تكون بين 1 و128 حرفًا. أرسلها مرة أخرى.");return true;}await dbPatch("tg_user_create_sessions",{password_ciphertext:encryptSecret(raw),step:"confirm",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});const fresh={...s,password_ciphertext:"stored",step:"confirm"};await showConfirm(fresh,m.chat.id);return true;}

export async function handleTelegramUserCreate(update:TgUpdate):Promise<boolean>{if(await callback(update))return true;if(await passwordMessage(update))return true;const m=update.message;if(!m?.text||!m.from)return false;const raw=m.text.trim();if(!isAddUserRequest(raw)&&!/^\/adduser(?:@\w+)?(?:\s|$)/i.test(raw))return false;const username=usernameFrom(raw.replace(/^\/adduser(?:@\w+)?/i,"أضف المستخدم"));if(!username){await send(m.chat.id,"➕ فهمت أنك تريد إضافة مستخدم. ارسل الاسم في نفس الرسالة، مثال:\n<code>أضف المستخدم AB-129</code>");return true;}return start(update,username);}
