import { decryptSecret } from "./telegram-crypto";
import { dbGet } from "./telegram-db";
import { agentInstallCommand } from "./router-agent";
import type { TgUpdate } from "./telegram-extra";

type BotUser={telegram_user_id:number;active_network_id?:string|null};
type Network={id:string;telegram_user_id:number;label:string;identity?:string|null;connection_mode:"direct"|"agent";agent_secret_ciphertext?:string|null;agent_version?:number|null;};
function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function send(chatId:number,text:string){const r=await fetch(`https://api.telegram.org/bot${token()}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true}),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);}
async function active(uid:number){const u=(await dbGet<BotUser>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id",limit:"1"}))[0];if(!u?.active_network_id)return null;return(await dbGet<Network>("tg_networks",{id:`eq.${u.active_network_id}`,telegram_user_id:`eq.${uid}`,select:"id,telegram_user_id,label,identity,connection_mode,agent_secret_ciphertext,agent_version",limit:"1"}))[0]??null;}

export async function handleAgentUpdate(update:TgUpdate):Promise<boolean>{const m=update.message;if(!m?.from)return false;const n=await active(m.from.id);if(!n){await send(m.chat.id,"📭 لا توجد شبكة نشطة.");return true;}if(n.connection_mode!=="agent"){await send(m.chat.id,`ℹ️ <b>${esc(n.identity||n.label)}</b> متصلة Direct API ولا تحتاج Agent.`);return true;}if(Number(n.agent_version||0)>=4){await send(m.chat.id,`✅ <b>${esc(n.identity||n.label)}</b>\nAgent v${esc(n.agent_version)} متصل بالفعل ولا يحتاج تحديث.`);return true;}if(!n.agent_secret_ciphertext){await send(m.chat.id,"🔴 لا أجد مفتاح Agent لهذه الشبكة. أعد ربطها عبر «إضافة شبكة → بدون Cloud» بدل إنشاء مفتاح جديد بصمت.");return true;}let secret="";try{secret=decryptSecret(n.agent_secret_ciphertext);}catch{await send(m.chat.id,"🔴 تعذر فك مفتاح Agent المخزن. لن أنشئ مفتاحًا بديلًا قد يقطع الاتصال.");return true;}const command=agentInstallCommand(n.id,secret);await send(m.chat.id,`⬆️ <b>تحديث Agent إلى v4 • ${esc(n.identity||n.label)}</b>\n━━━━━━━━━━━━━━━━━━\nانسخ السطر التالي والصقه في Terminal على MikroTik مرة واحدة:\n\n<code>${esc(command)}</code>\n\n✅ التحديث يستبدل فقط Script/Scheduler الخاص بالبوت <code>MT-TG-AGENT</code>.\n✅ لا يغير WAN أو Hotspot أو Firewall أو VLAN.\n🔒 الـAgent العادي يبقى Read/Test فقط؛ صلاحيات الإدارة الحساسة منفصلة.\n\nبعد أول Poll سيكتشف السيرفر v4 تلقائيًا.`);return true;}
