import { decryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert, dbPatch } from "./telegram-db";
import { RouterOSClient } from "./routeros-api";

type AlertKind="router_unreachable"|"agent_offline"|"internet_down"|"high_ping"|"packet_loss"|"cpu_high"|"ram_high"|"interface_down";
type Rule={id:string;telegram_user_id:number;network_id:string;kind:AlertKind;target?:string|null;threshold?:number|null;enabled:boolean;consecutive_failures:number;consecutive_recoveries:number;cooldown_minutes:number;config:Record<string,unknown>};
type State={rule_id:string;current_state:string;bad_count:number;good_count:number;last_value:Record<string,unknown>;active_since?:string|null;last_checked_at?:string|null;last_notified_at?:string|null;last_error?:string|null};
type Network={id:string;telegram_user_id:number;label:string;identity?:string|null;connection_mode:"direct"|"agent";host?:string|null;port?:number|null;username?:string|null;password_ciphertext?:string|null;protocol:"api"|"api-ssl";tls_verify:boolean;agent_last_seen_at?:string|null};
type AgentCommand={id:string;result?:Record<string,string>|null;created_at:string;completed_at?:string|null;status:string};
type Metrics={reachable:boolean;error?:string;cpu?:number;ram?:number;pingReplies?:number;pingCount?:number;avgPingMs?:number|null;lossPct?:number;interfaces:Map<string,{running:boolean;disabled:boolean;name:string}>;vlans:Map<number,{running:boolean;disabled:boolean;name:string}>;source:"direct"|"agent";telemetryAt?:string|null};
type Eval={available:boolean;bad?:boolean;title:string;detail:string;recovery:string;value:Record<string,unknown>;error?:string};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function send(chatId:number,text:string){const r=await fetch(`https://api.telegram.org/bot${token()}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true}),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);}
function clientFor(n:Network){if(n.connection_mode!=="direct"||!n.host||!n.port||!n.username||!n.password_ciphertext)throw new Error("Direct API credentials are incomplete");return new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:20000});}
function parseTimeMs(v?:string){if(!v)return null;let total=0,found=false;for(const m of v.matchAll(/([0-9.]+)(ms|us|µs|s)/g)){const n=Number(m[1]);if(!Number.isFinite(n))continue;found=true;total+=m[2]==="s"?n*1000:m[2]==="ms"?n:n/1000;}return found?total:null;}
function duration(ms:number){const min=Math.max(1,Math.round(ms/60000));if(min<60)return`${min} دقيقة`;const h=Math.floor(min/60),m=min%60;return m?`${h} ساعة و${m} دقيقة`:`${h} ساعة`;}

async function directMetrics(n:Network,rules:Rule[]):Promise<Metrics>{const out:Metrics={reachable:false,interfaces:new Map(),vlans:new Map(),source:"direct"};let c:RouterOSClient|undefined;try{c=clientFor(n);const rr=await c.command("/system/resource/print",["=.proplist=cpu-load,free-memory,total-memory"]);out.reachable=true;const r=rr[0]||{};out.cpu=Number(r["cpu-load"]||0);const total=Number(r["total-memory"]||0),free=Number(r["free-memory"]||0);out.ram=total?Math.round((1-free/total)*100):0;
  if(rules.some(x=>["internet_down","high_ping","packet_loss"].includes(x.kind))){try{const rows=await c.command("/ping",["=address=8.8.8.8","=count=4"]);const times=rows.map(x=>parseTimeMs(x.time)).filter((x):x is number=>x!==null);out.pingCount=4;out.pingReplies=times.length;out.lossPct=Math.round((1-times.length/4)*100);out.avgPingMs=times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length):0;}catch{out.pingCount=4;out.pingReplies=0;out.lossPct=100;out.avgPingMs=0;}}
  const targets=[...new Set(rules.filter(x=>x.kind==="interface_down"&&x.target).map(x=>String(x.target)))];for(const target of targets){if(target.startsWith("vlan:")){const id=Number(target.slice(5));try{const rows=await c.command("/interface/vlan/print",["=.proplist=name,vlan-id,running,disabled",`?vlan-id=${id}`]);const x=rows[0];if(x)out.vlans.set(id,{name:x.name||`VLAN ${id}`,running:x.running==="true",disabled:x.disabled==="true"});}catch{}}else{try{const rows=await c.command("/interface/print",["=.proplist=name,running,disabled",`?name=${target}`]);const x=rows[0];if(x)out.interfaces.set(target,{name:x.name||target,running:x.running==="true",disabled:x.disabled==="true"});}catch{}}}
  return out;}catch(e){out.error=e instanceof Error?e.message:String(e);return out;}finally{c?.close();}}

async function latestAgentStatus(n:Network){const rows=await dbGet<AgentCommand>("tg_agent_commands",{network_id:`eq.${n.id}`,kind:"eq.status",chat_id:"eq.0",status:"eq.success",select:"id,result,created_at,completed_at,status",order:"completed_at.desc",limit:"1"});return rows[0]??null;}
async function queueAgentTelemetry(n:Network,last:AgentCommand|null){const lastAt=last?.completed_at||last?.created_at;const fresh=lastAt&&Date.now()-new Date(lastAt).getTime()<45_000;if(fresh)return;const active=await dbGet<{id:string}>("tg_agent_commands",{network_id:`eq.${n.id}`,kind:"eq.status",chat_id:"eq.0",status:"in.(pending,claimed)",select:"id",limit:"1"});if(active.length)return;await dbInsert("tg_agent_commands",{network_id:n.id,telegram_user_id:n.telegram_user_id,chat_id:0,reply_message_id:null,kind:"status",payload:{telemetry:true},status:"pending"});}
async function agentMetrics(n:Network):Promise<Metrics>{const out:Metrics={reachable:true,interfaces:new Map(),vlans:new Map(),source:"agent"};const last=await latestAgentStatus(n);await queueAgentTelemetry(n,last);if(!last?.result||!last.completed_at||Date.now()-new Date(last.completed_at).getTime()>120_000){out.reachable=false;out.error="agent telemetry not ready or stale";return out;}const d=last.result;out.telemetryAt=last.completed_at;out.cpu=Number(d.cpu||0);const total=Number(d.total_memory||0),free=Number(d.free_memory||0);out.ram=total?Math.round((1-free/total)*100):0;out.pingCount=3;out.pingReplies=Number(d.ping_replies||0);out.lossPct=Math.round((1-(out.pingReplies||0)/3)*100);out.avgPingMs=null;return out;}

function evaluate(rule:Rule,n:Network,m:Metrics):Eval{const th=Number(rule.threshold||0);if(rule.kind==="agent_offline"){const age=n.agent_last_seen_at?Date.now()-new Date(n.agent_last_seen_at).getTime():Infinity;const bad=age>90_000;return{available:true,bad,title:"Agent غير متصل",detail:`آخر اتصال بالـAgent منذ ${Number.isFinite(age)?duration(age):"وقت غير معروف"}.`,recovery:"عاد Agent للاتصال بالسحابة.",value:{age_ms:Number.isFinite(age)?age:null,last_seen:n.agent_last_seen_at||null}};}
 if(rule.kind==="router_unreachable"){if(n.connection_mode==="agent")return{available:false,title:"الوصول للراوتر",detail:"",recovery:"",value:{},error:"use agent_offline for Agent networks"};return{available:true,bad:!m.reachable,title:"تعذر الوصول للراوتر",detail:m.error?`فشل اتصال Cloud بالـRouterOS API: ${m.error.slice(0,180)}`:"الراوتر لم يرد على API.",recovery:"عاد الاتصال بالراوتر من السحابة.",value:{reachable:m.reachable,error:m.error||null}};}
 if(!m.reachable)return{available:false,title:rule.kind,detail:"",recovery:"",value:{},error:m.error||"metrics unavailable"};
 if(rule.kind==="internet_down"){const replies=m.pingReplies??0;return{available:true,bad:replies===0,title:"الإنترنت لا يرد",detail:`لم يصل أي رد من 8.8.8.8 (${replies}/${m.pingCount||3}).`,recovery:"عاد الإنترنت للرد من الراوتر.",value:{replies,count:m.pingCount,loss_pct:m.lossPct,source:m.source,telemetry_at:m.telemetryAt||null}};}
 if(rule.kind==="packet_loss")return{available:true,bad:(m.lossPct??0)>th,title:"Packet loss مرتفع",detail:`الفقد الحالي ${m.lossPct??0}%، والحد ${th}%.`,recovery:`عاد Packet loss تحت ${th}%.`,value:{loss_pct:m.lossPct,threshold:th,source:m.source}};
 if(rule.kind==="high_ping"){if(m.avgPingMs==null)return{available:false,title:"Ping مرتفع",detail:"",recovery:"",value:{},error:"Agent STATUS does not expose latency milliseconds"};return{available:true,bad:m.avgPingMs>th,title:"Ping مرتفع",detail:`متوسط Ping الحالي ${m.avgPingMs}ms، والحد ${th}ms.`,recovery:`عاد Ping تحت ${th}ms.`,value:{avg_ping_ms:m.avgPingMs,threshold:th}};}
 if(rule.kind==="cpu_high")return{available:true,bad:(m.cpu??0)>th,title:"استخدام CPU مرتفع",detail:`CPU الآن ${m.cpu??0}%، والحد ${th}%.`,recovery:`عاد CPU تحت ${th}%.`,value:{cpu:m.cpu,threshold:th,source:m.source}};
 if(rule.kind==="ram_high")return{available:true,bad:(m.ram??0)>th,title:"استخدام RAM مرتفع",detail:`RAM الآن ${m.ram??0}%، والحد ${th}%.`,recovery:`عادت RAM تحت ${th}%.`,value:{ram:m.ram,threshold:th,source:m.source}};
 if(rule.kind==="interface_down"){if(n.connection_mode==="agent")return{available:false,title:"Interface/VLAN",detail:"",recovery:"",value:{},error:"target-state telemetry not implemented for Agent yet"};const t=String(rule.target||"");if(t.startsWith("vlan:")){const id=Number(t.slice(5)),x=m.vlans.get(id);if(!x)return{available:true,bad:true,title:`VLAN ${id} غير موجود`,detail:`لم أجد VLAN ID ${id} على الراوتر.`,recovery:`عاد VLAN ${id} للظهور والعمل.`,value:{target:t,found:false}};return{available:true,bad:x.disabled||!x.running,title:`VLAN ${id} متوقف`,detail:`${x.name}: running=${x.running?"yes":"no"}, disabled=${x.disabled?"yes":"no"}.`,recovery:`VLAN ${id} عاد Running.`,value:{target:t,name:x.name,running:x.running,disabled:x.disabled}};}const x=m.interfaces.get(t);if(!x)return{available:true,bad:true,title:`Interface ${t} غير موجود`,detail:`لم أجد Interface باسم ${t}.`,recovery:`عاد Interface ${t} للظهور والعمل.`,value:{target:t,found:false}};return{available:true,bad:x.disabled||!x.running,title:`Interface ${t} متوقف`,detail:`running=${x.running?"yes":"no"}, disabled=${x.disabled?"yes":"no"}.`,recovery:`Interface ${t} عاد Running.`,value:{target:t,running:x.running,disabled:x.disabled}};}
 return{available:false,title:rule.kind,detail:"",recovery:"",value:{},error:"unsupported rule"};}

async function getState(id:string){return(await dbGet<State>("tg_alert_state",{rule_id:`eq.${id}`,select:"*",limit:"1"}))[0]??null;}
async function save(id:string,old:State|null,patch:Record<string,unknown>){const p={...patch,updated_at:new Date().toISOString()};if(old)await dbPatch("tg_alert_state",p,{rule_id:`eq.${id}`});else await dbInsert("tg_alert_state",{rule_id:id,current_state:"unknown",bad_count:0,good_count:0,last_value:{},...p});}
async function transition(rule:Rule,n:Network,ev:Eval){const now=new Date(),old=await getState(rule.id);if(!ev.available){await save(rule.id,old,{last_checked_at:now.toISOString(),last_error:ev.error||"unavailable"});return;}const was=old?.current_state==="alert";if(ev.bad){const bad=(old?.bad_count||0)+1,fire=!was&&bad>=rule.consecutive_failures,activeSince=was?(old?.active_since||now.toISOString()):(fire?now.toISOString():old?.active_since||null);if(fire)await send(rule.telegram_user_id,`🔴 <b>${esc(n.identity||n.label)} • تنبيه</b>\n━━━━━━━━━━━━━━━━━━\n⚠️ <b>${esc(ev.title)}</b>\n${esc(ev.detail)}\n\n✅ تم التأكيد بعد <b>${rule.consecutive_failures}</b> فحوص متتالية.\n🔕 لن أكرر نفس التنبيه حتى ترجع الحالة طبيعية.`);await save(rule.id,old,{current_state:fire||was?"alert":(old?.current_state||"unknown"),bad_count:bad,good_count:0,last_value:ev.value,active_since:activeSince,last_checked_at:now.toISOString(),last_notified_at:fire?now.toISOString():old?.last_notified_at||null,last_error:null});return;}const good=(old?.good_count||0)+1;if(was&&good>=rule.consecutive_recoveries){const since=old?.active_since?new Date(old.active_since).getTime():now.getTime();await send(rule.telegram_user_id,`🟢 <b>${esc(n.identity||n.label)} • عادت طبيعية</b>\n━━━━━━━━━━━━━━━━━━\n✅ ${esc(ev.recovery)}\n⏱ مدة الحالة تقريبًا: <b>${esc(duration(now.getTime()-since))}</b>.`);await save(rule.id,old,{current_state:"normal",bad_count:0,good_count:good,last_value:ev.value,active_since:null,last_checked_at:now.toISOString(),last_notified_at:now.toISOString(),last_error:null});return;}await save(rule.id,old,{current_state:was?"alert":"normal",bad_count:0,good_count:good,last_value:ev.value,last_checked_at:now.toISOString(),last_error:null});}

export async function runAlertChecksV2(){const rules=await dbGet<Rule>("tg_alert_rules",{enabled:"eq.true",select:"*",order:"network_id.asc",limit:"200"});const groups=new Map<string,Rule[]>();for(const r of rules){const a=groups.get(r.network_id)||[];a.push(r);groups.set(r.network_id,a);}const out:Array<{network_id:string;checked:number;transport:string}>=[];for(const [networkId,rs] of groups){const n=(await dbGet<Network>("tg_networks",{id:`eq.${networkId}`,select:"*",limit:"1"}))[0];if(!n)continue;let m:Metrics;try{m=n.connection_mode==="agent"?await agentMetrics(n):await directMetrics(n,rs);}catch(e){m={reachable:false,error:e instanceof Error?e.message:String(e),interfaces:new Map(),vlans:new Map(),source:n.connection_mode};}for(const r of rs){try{await transition(r,n,evaluate(r,n,m));}catch(e){console.error("alert-v2 rule failed",r.id,e);}}out.push({network_id:networkId,checked:rs.length,transport:n.connection_mode});}return out;}
