import { decryptSecret } from "./telegram-crypto";
import { dbGet } from "./telegram-db";
import type { TgUpdate } from "./telegram-extra";

type Batch={id:string;telegram_user_id:number;network_id:string;source:string;profile:string;password_mode:"none"|"same"|"random";username_mode:string;requested_count:number;created_count:number;failed_count:number;status:string;created_at:string};
type Item={id:string;batch_id:string;seq:number;username:string;password_ciphertext?:string|null;router_created:boolean;error_text?:string|null};
type Network={id:string;label:string;identity?:string|null};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function tg(method:string,payload:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
function send(chatId:number,text:string,reply_markup?:unknown){return tg("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}
async function answer(id:string,text?:string){try{await tg("answerCallbackQuery",{callback_query_id:id,text});}catch{}}
async function sendCsv(chatId:number,filename:string,csv:string,caption:string){const form=new FormData();form.append("chat_id",String(chatId));form.append("caption",caption.slice(0,1000));form.append("parse_mode","HTML");form.append("document",new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),filename);const r=await fetch(`https://api.telegram.org/bot${token()}/sendDocument`,{method:"POST",body:form,cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}

function passLabel(mode:Batch["password_mode"]){return mode==="none"?"Username فقط":mode==="same"?"Password = Username":"كلمة مرور عشوائية";}
function csvEscape(value:unknown){const s=String(value??"");return /[",\r\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
async function batches(uid:number,limit=20){return dbGet<Batch>("tg_card_batches",{telegram_user_id:`eq.${uid}`,select:"*",order:"created_at.desc",limit:String(limit)});}
async function network(id:string){return (await dbGet<Network>("tg_networks",{id:`eq.${id}`,select:"id,label,identity",limit:"1"}))[0]??null;}
async function resolveBatch(uid:number,ref:string){const rows=await batches(uid,50);if(/^\d+$/.test(ref)){const i=Number(ref)-1;return i>=0&&i<rows.length?rows[i]:null;}const normalized=ref.replace(/[^a-f0-9-]/gi,"");return rows.find(b=>b.id===normalized||b.id.startsWith(normalized))??null;}

function rowButtons(batch:Batch){return [[{text:"🖨 طباعة",callback_data:`pc:start:${batch.id}`},{text:"📊 CSV",callback_data:`bt:csv:${batch.id}`}]];}

async function showBatches(update:TgUpdate){const m=update.message;if(!m?.from)return false;const rows=await batches(m.from.id,12);if(!rows.length){await send(m.chat.id,"📭 لا توجد دفعات كروت محفوظة بعد.\nمثال: <code>سوي 60 كرت</code>");return true;}const lines:string[]=[];for(let i=0;i<rows.length;i++){const b=rows[i];const n=await network(b.network_id);const date=new Intl.DateTimeFormat("ar-YE",{timeZone:"Asia/Aden",dateStyle:"short",timeStyle:"short"}).format(new Date(b.created_at));lines.push(`${i+1}. <b>${esc(b.profile)}</b> • ${b.created_count}/${b.requested_count}\n   📡 ${esc(n?.identity||n?.label||"-")} • 🔑 ${esc(passLabel(b.password_mode))}\n   🕓 ${esc(date)} • 🆔 <code>${b.id.slice(0,8)}</code>`);}await send(m.chat.id,`🗂 <b>دفعات الكروت</b>\n━━━━━━━━━━━━━━━━━━\n${lines.join("\n\n")}\n\nلإعادة الطباعة: <code>اطبع الدفعة 2</code>\nللتصدير: <code>CSV الدفعة 2</code>`);return true;}

async function startPrintByRef(update:TgUpdate,ref:string){const m=update.message;if(!m?.from)return false;const b=await resolveBatch(m.from.id,ref);if(!b){await send(m.chat.id,"❌ لم أجد هذه الدفعة. أرسل <code>/batches</code> لعرض الدفعات.");return true;}const fake:TgUpdate={...update,callback_query:{id:`local-${Date.now()}`,from:m.from,message:m,data:`pc:start:${b.id}`}};return false; // handled below by direct print-session creation helper
}

async function createPrintSession(chatId:number,uid:number,b:Batch){const rows=await (await import("./telegram-db")).dbInsert<any>("tg_print_sessions",{telegram_user_id:uid,chat_id:chatId,batch_id:b.id,step:"await_template"},"*");const s=rows[0];if(!s)throw new Error("تعذر بدء جلسة الطباعة");const templates=await dbGet<any>("tg_print_templates",{telegram_user_id:`eq.${uid}`,select:"*",order:"created_at.desc",limit:"1"});const kb=templates[0]?{inline_keyboard:[[{text:"📁 استخدم آخر قالب",callback_data:`pc:last:${s.id}`}],[{text:"❌ إلغاء",callback_data:`pc:no:${s.id}`}]]}:{inline_keyboard:[[{text:"❌ إلغاء",callback_data:`pc:no:${s.id}`}]]};await send(chatId,`🖨 <b>إعادة طباعة دفعة</b>\n━━━━━━━━━━━━━━━━━━\n🎫 ${b.created_count} كرت • 🏷 ${esc(b.profile)}\n🔑 ${esc(passLabel(b.password_mode))}\n\nأرسل قالب كرت واحد PNG/JPG/PDF، أو استخدم آخر قالب محفوظ.`,kb);}

async function exportBatchCsv(chatId:number,uid:number,b:Batch){const items=await dbGet<Item>("tg_card_batch_items",{batch_id:`eq.${b.id}`,select:"*",order:"seq.asc",limit:"200"});if(!items.length){await send(chatId,"📭 هذه الدفعة لا تحتوي عناصر محفوظة.");return true;}const lines=["seq,username,password,profile,status,error"];for(const item of items){let password="";if(item.router_created){if(b.password_mode==="same")password=item.username;else if(b.password_mode==="random"&&item.password_ciphertext){try{password=decryptSecret(item.password_ciphertext);}catch{password="";}}}lines.push([item.seq,item.username,password,b.profile,item.router_created?"created":"failed",item.error_text||""].map(csvEscape).join(","));}await sendCsv(chatId,`cards-${b.id.slice(0,8)}.csv`,lines.join("\r\n"),`📊 <b>تصدير دفعة الكروت</b>\n🎫 ${b.created_count}/${b.requested_count} • 🏷 ${esc(b.profile)}\n🔑 ${esc(passLabel(b.password_mode))}`);return true;}

async function callback(update:TgUpdate){const cb=update.callback_query;if(!cb?.data||!/^bt:csv:/.test(cb.data))return false;const id=cb.data.slice("bt:csv:".length);const b=(await dbGet<Batch>("tg_card_batches",{id:`eq.${id}`,telegram_user_id:`eq.${cb.from.id}`,select:"*",limit:"1"}))[0];if(!b){await answer(cb.id,"الدفعة غير موجودة");return true;}await answer(cb.id,"جاري تجهيز CSV…");return exportBatchCsv(cb.message?.chat.id??cb.from.id,cb.from.id,b);}

export async function handleTelegramCardBatchTools(update:TgUpdate):Promise<boolean>{if(await callback(update))return true;const m=update.message;if(!m?.text||!m.from)return false;const raw=m.text.trim();if(/^\/(?:batches|cardbatches)(?:@\w+)?$/i.test(raw)||/(?:دفعاتي|دفعات الكروت|قائمه الدفعات|قائمة الدفعات)/i.test(raw))return showBatches(update);let match=raw.match(/(?:اطبع|طباعة|طباعه|print)\s*(?:لي\s*)?(?:ال)?دفعة\s*([a-f0-9-]{4,36}|\d+)/i);if(match){const b=await resolveBatch(m.from.id,match[1]);if(!b){await send(m.chat.id,"❌ لم أجد هذه الدفعة.");return true;}await createPrintSession(m.chat.id,m.from.id,b);return true;}match=raw.match(/(?:csv|اكسل|excel|صدر|تصدير)\s*(?:لي\s*)?(?:ال)?دفعة\s*([a-f0-9-]{4,36}|\d+)/i);if(match){const b=await resolveBatch(m.from.id,match[1]);if(!b){await send(m.chat.id,"❌ لم أجد هذه الدفعة.");return true;}return exportBatchCsv(m.chat.id,m.from.id,b);}if(/^\/batchcsv(?:@\w+)?\s+(.+)/i.test(raw)){const ref=raw.replace(/^\/batchcsv(?:@\w+)?\s+/i,"").trim();const b=await resolveBatch(m.from.id,ref);if(!b){await send(m.chat.id,"❌ لم أجد هذه الدفعة.");return true;}return exportBatchCsv(m.chat.id,m.from.id,b);}return false;}
