import { decryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert } from "./telegram-db";
import { RouterOSClient } from "./routeros-api";
import { normalizeLocalText } from "./telegram-nlu-v2";
import type { TgUpdate } from "./telegram-extra";

type Network={id:string;telegram_user_id:number;label:string;identity?:string|null;router_os_version?:string|null;connection_mode:"direct"|"agent";host?:string|null;port?:number|null;username?:string|null;password_ciphertext?:string|null;protocol:"api"|"api-ssl";tls_verify:boolean;agent_last_seen_at?:string|null};
type BotUser={telegram_user_id:number;active_network_id?:string|null};
type Match={username:string;source:string;profile:string;disabled:boolean;score:number};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function send(chatId:number,text:string){const r=await fetch(`https://api.telegram.org/bot${token()}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true}),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
async function activeNetwork(uid:number){const u=(await dbGet<BotUser>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id",limit:"1"}))[0];if(!u?.active_network_id)return null;return (await dbGet<Network>("tg_networks",{id:`eq.${u.active_network_id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}
function client(n:Network){if(n.connection_mode!=="direct"||!n.host||!n.port||!n.username||!n.password_ciphertext)throw new Error("Direct API unavailable");return new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:25000});}
function clean(v:string){return normalizeLocalText(v).toLowerCase().replace(/\s+/g,"");}
function score(name:string,q:string){const n=clean(name),x=clean(q);if(n===x)return 0;if(n.startsWith(x))return 1;if(n.includes(x))return 2;if(x.startsWith(n))return 3;return 10;}
function queryFrom(raw:string){const text=raw.trim();const cmd=/^\/(?:users|finduser|searchuser|userfind)(?:@\w+)?(?:\s+(.+))?$/i.exec(text);if(cmd)return{recognized:true,query:(cmd[1]||"").trim()};const n=normalizeLocalText(text);if(/^(?:المستخدمين|المستخدمون|اليوزرات|الكروت|users|user list)$/i.test(n))return{recognized:true,query:""};if(!/(?:ابحث|دور|دوّر|فتش|لق|find|search|lookup)/i.test(n))return{recognized:false,query:""};if(!/(?:مستخدم|يوزر|كرت|مشترك|user|card|account)/i.test(n))return{recognized:false,query:""};let q=text.match(/(?:مستخدم|المستخدم|يوزر|اليوزر|كرت|الكرت|مشترك|user|card|account)\s*(?:اسمه|اسم|name)?\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{1,128})/iu)?.[1]||"";if(!q)q=text.match(/(?:عن|for)\s+([\p{L}\p{N}_.@:+-]{1,128})/iu)?.[1]||"";return{recognized:true,query:q.trim()};}
async function collect(c:RouterOSClient,query:string){const out:Match[]=[];const q=clean(query);const add=(username:string,source:string,profile:string,disabled:string)=>{if(!username)return;const s=query?score(username,query):5;if(query&&s>=10)return;out.push({username,source,profile:profile||"-",disabled:disabled==="true"||disabled==="yes",score:s});};
  try{const rows=await c.command("/ip/hotspot/user/print",["=.proplist=name,profile,disabled"]);for(const r of rows)add(r.name||"","Hotspot",r.profile||"",r.disabled||"");}catch{}
  let version="";try{version=(await c.command("/system/resource/print",["=.proplist=version"]))[0]?.version||"";}catch{}const major=Number(/^\d+/.exec(version)?.[0]||0);
  if(major>=7){try{const rows=await c.command("/user-manager/user/print",["=.proplist=name,group,disabled"]);for(const r of rows)add(r.name||"","User Manager v7",r.group||"",r.disabled||"");}catch{}}
  else{try{const rows=await c.command("/tool/user-manager/user/print",["=.proplist=username,actual-profile,disabled"]);for(const r of rows)add(r.username||"","User Manager v6",r["actual-profile"]||"",r.disabled||"");}catch{}}
  const seen=new Set<string>();return out.sort((a,b)=>a.score-b.score||a.username.localeCompare(b.username)).filter(x=>{const k=`${x.source}:${x.username}`.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;});}
function render(n:Network,rows:Match[],query:string){const title=query?`🔎 <b>نتائج البحث عن ${esc(query)}</b>`:`👥 <b>المستخدمون • ${esc(n.identity||n.label)}</b>`;if(!rows.length)return `${title}\n━━━━━━━━━━━━━━━━━━\nلم أجد مستخدمًا مطابقًا.\n\nجرّب الاسم كاملًا أو جزءًا منه، مثل: <code>/users AB12</code>`;const shown=rows.slice(0,20);return `${title}\n━━━━━━━━━━━━━━━━━━\n${query?`وجدت <b>${rows.length}</b> نتيجة مطابقة.`:`إجمالي الحسابات التي قرأتها: <b>${rows.length}</b>. أعرض أول 20 فقط؛ اكتب جزءًا من الاسم للبحث.`}\n\n${shown.map((r,i)=>`${i+1}. ${r.disabled?"⛔":"🟢"} <code>${esc(r.username)}</code>\n   ${esc(r.source)} • ${esc(r.profile)}`).join("\n\n")}\n\n💡 للفحص الكامل: <code>/card USERNAME</code>\n⚙️ مثال: «غير باقة USERNAME إلى 500»`;} 

export async function handleTelegramUserSearch(update:TgUpdate):Promise<boolean>{const m=update.message;if(!m?.text||!m.from)return false;const parsed=queryFrom(m.text);if(!parsed.recognized)return false;const n=await activeNetwork(m.from.id);if(!n){await send(m.chat.id,"📭 لا توجد شبكة نشطة.");return true;}if(n.connection_mode==="agent"){if(!parsed.query){await send(m.chat.id,"👥 البحث العام عبر Agent سيُفعّل مع User Admin Agent. حاليًا اكتب اسم المستخدم أو الكرت كاملًا، مثل <code>/card AB12</code>.");return true;}const online=n.agent_last_seen_at?Date.now()-new Date(n.agent_last_seen_at).getTime()<60_000:false;const waiting=await send(m.chat.id,`${online?"🔎":"🟠"} <b>${esc(n.identity||n.label)}</b>\nأبحث عن <code>${esc(parsed.query)}</code> عبر Agent…`);await dbInsert("tg_agent_commands",{network_id:n.id,telegram_user_id:m.from.id,chat_id:m.chat.id,reply_message_id:waiting.message_id,kind:"card",payload:{username:parsed.query},status:"pending"});return true;}const c=client(n);try{const rows=await collect(c,parsed.query);await send(m.chat.id,render(n,rows,parsed.query));return true;}catch(e){await send(m.chat.id,`🔴 تعذر البحث في المستخدمين.\n<code>${esc(e instanceof Error?e.message:e)}</code>`);return true;}finally{c.close();}}
