import { decryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert, dbPatch } from "./telegram-db";
import { normalizeLocalText, type LocalNluContext } from "./telegram-nlu-v2";
import { RouterOSClient } from "./routeros-api";
import type { TgUpdate } from "./telegram-extra";

type BotUser={telegram_user_id:number;active_network_id?:string|null};
type Network={id:string;telegram_user_id:number;label:string;connection_mode:"direct"|"agent";host?:string|null;port?:number|null;username?:string|null;password_ciphertext?:string|null;protocol:"api"|"api-ssl";tls_verify:boolean;identity?:string|null;router_os_version?:string|null};
type PendingAction={id:string;telegram_user_id:number;chat_id:number;network_id:string;action_type:ActionType;target_type:"user"|"vlan";target_value:string;preview:Record<string,unknown>;status:string;expires_at:string;created_at:string};
type ActionType="disconnect_user"|"disable_hotspot_user"|"enable_hotspot_user"|"disable_vlan"|"enable_vlan";
type ParsedAction={action_type:ActionType;target_type:"user"|"vlan";target_value:string};
type UserResolution={active:Record<string,string>[];source:"hotspot"|"user-manager-v6"|"user-manager-v7"|null;entry:Record<string,string>|null;version:string};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function telegram(method:string,payload:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
function send(chatId:number,text:string,reply_markup?:unknown){return telegram("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}
async function edit(chatId:number,messageId:number,text:string,reply_markup?:unknown){try{return await telegram("editMessageText",{chat_id:chatId,message_id:messageId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}catch{return null;}}
async function answer(id:string,text?:string){try{await telegram("answerCallbackQuery",{callback_query_id:id,text,show_alert:false});}catch{}}

async function activeNetwork(uid:number){const u=(await dbGet<BotUser>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id",limit:"1"}))[0];if(!u?.active_network_id)return null;return (await dbGet<Network>("tg_networks",{id:`eq.${u.active_network_id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}
function clientFor(n:Network){if(n.connection_mode!=="direct"||!n.host||!n.port||!n.username||!n.password_ciphertext)throw new Error("هذه العملية تحتاج اتصال Direct API أو Privileged Agent مفعّل.");return new RouterOSClient({host:n.host,port:n.port,username:n.username,password:decryptSecret(n.password_ciphertext),tls:n.protocol==="api-ssl",rejectUnauthorized:n.tls_verify,timeoutMs:20000});}
async function nluContext(uid:number){return (await dbGet<LocalNluContext>("tg_nlu_context",{telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}

const blocked=new Set(["الشبكه","الشبكة","شبكه","شبكة","الراوتر","راوتر","router","network","vlan","فيلان","المستخدم","مستخدم","الكرت","كرت","اليوزر","يوزر","هذا","هذه","هذي","ذا","الحين","الان","الآن"]);
function userCandidate(v:string|undefined|null){if(!v)return null;const x=v.trim().replace(/^["'«]+|["'»،,.!?]+$/g,"");if(x.length<2||x.length>128||!/^[\p{L}\p{N}_.@:+-]+$/u.test(x))return null;if(blocked.has(normalizeLocalText(x)))return null;return x;}
function extractUser(raw:string){const q=raw.match(/["'«]([^"'»]{2,128})["'»]/u)?.[1];const qc=userCandidate(q);if(qc)return qc;const noun=raw.match(/(?:كرت|الكرت|يوزر|اليوزر|مستخدم|المستخدم|مشترك|user|card|account)(?=$|\s|[:#-])\s*(?:رقم|اسم|اسمه|name|number)?\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{2,128})/iu)?.[1];const nc=userCandidate(noun);if(nc)return nc;const verb=raw.match(/(?:افصل|فصل|اطرد|اخرج|طلع|عطل|عطّل|وقف|اقفل|سكر|فعل|فعّل|شغل|رجع|افتح|disconnect|kick|logout|disable|block|enable|unblock)(?=$|\s)\s*(?:هذا|هذه|هذي|ذا|the)?\s*(?:الكرت|كرت|اليوزر|يوزر|المستخدم|مستخدم|user|card)?\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{2,128})/iu)?.[1];return userCandidate(verb);}
function extractVlan(raw:string){const m=raw.match(/(?:vlan|فيلان|فلان)\s*#?\s*(\d{1,4})/i);const n=Number(m?.[1]||0);return n>=1&&n<=4094?n:null;}
function parseAction(raw:string,ctx:LocalNluContext|null):ParsedAction|null{const n=normalizeLocalText(raw.replace(/^\//,""));const disconnect=/(?:^|\s)(?:افصل|فصل|اطرد|اخرج|طلع|disconnect|kick|logout)(?:\s|$)/i.test(n);const disable=/(?:^|\s)(?:عطل|عطّل|وقف|اقفل|سكر|disable|block)(?:\s|$)/i.test(n);const enable=/(?:^|\s)(?:فعل|فعّل|شغل|رجع|افتح|enable|unblock)(?:\s|$)/i.test(n);if(!disconnect&&!disable&&!enable)return null;
  const explicitVlan=extractVlan(raw);const mentionsVlan=/(?:vlan|فيلان|فلان)/i.test(n);if(explicitVlan&&(disable||enable))return{action_type:disable?"disable_vlan":"enable_vlan",target_type:"vlan",target_value:String(explicitVlan)};
  if(mentionsVlan&&ctx?.last_entity_type==="vlan"&&ctx.last_entity_value&&(disable||enable))return{action_type:disable?"disable_vlan":"enable_vlan",target_type:"vlan",target_value:ctx.last_entity_value};
  let user=extractUser(raw);const mentionsUser=/(?:كرت|يوزر|مستخدم|مشترك|user|card|account)/i.test(n);if(!user&&ctx?.last_entity_type==="card"&&ctx.last_entity_value&&(mentionsUser||/(?:ه|ها|هذا|هذه|هذي|ذا)$/i.test(n)))user=ctx.last_entity_value;
  if(!user)return null;if(disconnect)return{action_type:"disconnect_user",target_type:"user",target_value:user};if(disable)return{action_type:"disable_hotspot_user",target_type:"user",target_value:user};if(enable)return{action_type:"enable_hotspot_user",target_type:"user",target_value:user};return null;}

async function audit(p:{telegram_user_id:number;chat_id:number;network_id?:string|null;pending_action_id?:string|null;action_type:string;target_type?:string|null;target_value?:string|null;phase:string;details?:Record<string,unknown>}){await dbInsert("tg_action_audit",{...p,details:p.details||{}});}
async function resolveUser(c:RouterOSClient,username:string):Promise<UserResolution>{const active=await c.command("/ip/hotspot/active/print",["=.proplist=.id,user,address,mac-address,server,uptime",`?user=${username}`]);const local=await c.command("/ip/hotspot/user/print",["=.proplist=.id,name,profile,disabled",`?name=${username}`]);const res=await c.command("/system/resource/print",["=.proplist=version"]);const version=res[0]?.version||"";if(local[0])return{active,source:"hotspot",entry:local[0],version};const major=Number(/^\d+/.exec(version)?.[0]||0);try{if(major>=7){const um=await c.command("/user-manager/user/print",["=.proplist=.id,name,group,disabled",`?name=${username}`]);if(um[0])return{active,source:"user-manager-v7",entry:um[0],version};}else{const um=await c.command("/tool/user-manager/user/print",["=.proplist=.id,username,actual-profile,disabled",`?username=${username}`]);if(um[0])return{active,source:"user-manager-v6",entry:um[0],version};}}catch{}return{active,source:null,entry:null,version};}
async function resolveVlan(c:RouterOSClient,id:number){const rows=await c.command("/interface/vlan/print",["=.proplist=.id,name,vlan-id,interface,disabled,running",`?vlan-id=${id}`]);const row=rows[0];if(!row)return null;let affected=0;try{const servers=await c.command("/ip/hotspot/print",["=.proplist=name,interface,disabled"]);const serverNames=new Set(servers.filter(x=>x.interface===row.name&&x.disabled!=="true").map(x=>x.name));if(serverNames.size){const active=await c.command("/ip/hotspot/active/print",["=.proplist=server"]);affected=active.filter(x=>serverNames.has(x.server)).length;}}catch{}return{row,affected};}
function sourceLabel(v:UserResolution["source"]){return v==="hotspot"?"Hotspot Local User":v==="user-manager-v6"?"User Manager v6":v==="user-manager-v7"?"User Manager v7":"غير معروف";}
function actionLabel(a:ActionType){return({disconnect_user:"فصل الجلسة",disable_hotspot_user:"تعطيل المستخدم",enable_hotspot_user:"تفعيل المستخدم",disable_vlan:"تعطيل VLAN",enable_vlan:"تفعيل VLAN"} as Record<ActionType,string>)[a];}

async function createPreview(update:TgUpdate,parsed:ParsedAction){const m=update.message;if(!m?.from)return false;const n=await activeNetwork(m.from.id);if(!n){await send(m.chat.id,"📭 لا توجد شبكة نشطة.");return true;}if(n.connection_mode!=="direct"){await send(m.chat.id,"🔐 <b>هذه الشبكة تعمل عبر Agent القراءة الآمنة.</b>\nعمليات التعديل تحتاج Privileged Agent opt-in منفصل، ولن أرفع صلاحيات الراوتر تلقائيًا.");return true;}const c=clientFor(n);try{let preview:Record<string,unknown>={network:n.identity||n.label};let body="";
    if(parsed.target_type==="user"){const r=await resolveUser(c,parsed.target_value);if(parsed.action_type==="disconnect_user"){if(!r.active.length){await send(m.chat.id,`ℹ️ <b>${esc(parsed.target_value)}</b> غير متصل الآن؛ لا توجد جلسة لأفصلها.`);return true;}preview={...preview,session_count:r.active.length,ips:r.active.map(x=>x.address).filter(Boolean).slice(0,8)};body=`👤 المستخدم: <code>${esc(parsed.target_value)}</code>\n🟢 الجلسات الحالية: <b>${r.active.length}</b>${r.active[0]?.address?`\n📍 IP: <code>${esc(r.active[0].address)}</code>`:""}\n\n⚠️ سيؤدي التأكيد إلى فصل الجلسات الحالية فقط. لن أحذف الكرت ولن أغيّر الباقة.`;}else{if(!r.entry||!r.source){await send(m.chat.id,`❌ لم أجد المستخدم <code>${esc(parsed.target_value)}</code> في Hotspot أو User Manager. لم أنفذ شيئًا.`);return true;}const disabled=r.entry.disabled==="true"||r.entry.disabled==="yes";if(parsed.action_type==="disable_hotspot_user"&&disabled){await send(m.chat.id,`ℹ️ المستخدم <code>${esc(parsed.target_value)}</code> معطل أصلًا في ${esc(sourceLabel(r.source))}.`);return true;}if(parsed.action_type==="enable_hotspot_user"&&!disabled){await send(m.chat.id,`ℹ️ المستخدم <code>${esc(parsed.target_value)}</code> مفعّل أصلًا في ${esc(sourceLabel(r.source))}.`);return true;}preview={...preview,source:r.source,profile:r.entry.profile||r.entry["actual-profile"]||r.entry.group||null,currently_disabled:disabled,active_sessions:r.active.length};body=`👤 المستخدم: <code>${esc(parsed.target_value)}</code>\n📚 المصدر: <b>${esc(sourceLabel(r.source))}</b>\n🏷 الباقة/المجموعة: <b>${esc(r.entry.profile||r.entry["actual-profile"]||r.entry.group||"-")}</b>\n🚦 الحالة الآن: ${disabled?"⛔ معطل":"🟢 مفعّل"}${r.active.length?`\n👥 جلسات نشطة: <b>${r.active.length}</b>`:""}\n\n⚠️ ${parsed.action_type==="disable_hotspot_user"?"سيمنع تسجيل دخول جديد. الجلسة الحالية لن أفصلها تلقائيًا.":"سيعيد السماح للمستخدم بالمصادقة وفق إعداداته الحالية."}`;}}
    else{const id=Number(parsed.target_value);const v=await resolveVlan(c,id);if(!v){await send(m.chat.id,`❌ VLAN ${id} غير موجود. لم أنفذ شيئًا.`);return true;}const disabled=v.row.disabled==="true";if(parsed.action_type==="disable_vlan"&&disabled){await send(m.chat.id,`ℹ️ VLAN ${id} معطل أصلًا.`);return true;}if(parsed.action_type==="enable_vlan"&&!disabled){await send(m.chat.id,`ℹ️ VLAN ${id} مفعّل أصلًا.`);return true;}preview={...preview,name:v.row.name,parent:v.row.interface,currently_disabled:disabled,affected_hotspot_users:v.affected};body=`🧩 VLAN: <b>${id}</b> — ${esc(v.row.name||"-")}\n🔗 Parent: ${esc(v.row.interface||"-")}\n🚦 الحالة الآن: ${disabled?"⛔ معطل":"🟢 مفعّل"}${v.affected?`\n👥 Hotspot متصلون قد يتأثرون: <b>${v.affected}</b>`:""}\n\n⚠️ ${parsed.action_type==="disable_vlan"?"تعطيل VLAN قد يقطع كل الترافيك والخدمات التي تعتمد عليها.":"سيتم تفعيل واجهة VLAN فقط؛ لن أغيّر DHCP/Hotspot/Firewall."}`;}
    const rows=await dbInsert<PendingAction>("tg_pending_actions",{telegram_user_id:m.from.id,chat_id:m.chat.id,network_id:n.id,action_type:parsed.action_type,target_type:parsed.target_type,target_value:parsed.target_value,preview,status:"pending"},"*");const a=rows[0];if(!a)throw new Error("تعذر إنشاء طلب التأكيد");await audit({telegram_user_id:m.from.id,chat_id:m.chat.id,network_id:n.id,pending_action_id:a.id,action_type:a.action_type,target_type:a.target_type,target_value:a.target_value,phase:"preview",details:preview});await send(m.chat.id,`🛡 <b>تأكيد مطلوب • ${esc(actionLabel(a.action_type))}</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n${body}\n\n⏳ التأكيد صالح لمدة 10 دقائق.`,{inline_keyboard:[[{text:"✅ تأكيد التنفيذ",callback_data:`priv:ok:${a.id}`}],[{text:"❌ إلغاء",callback_data:`priv:no:${a.id}`}]]});return true;
  }catch(e){await send(m.chat.id,`🔴 تعذر تجهيز المعاينة.\n<code>${esc(e instanceof Error?e.message:e)}</code>`);return true;}finally{c.close();}}

async function execute(action:PendingAction,n:Network){const c=clientFor(n);try{if(action.action_type==="disconnect_user"){const r=await resolveUser(c,action.target_value);if(!r.active.length)return{message:"المستخدم لم يعد متصلًا؛ لا توجد جلسة لفصلها.",changed:0};let changed=0;for(const s of r.active){const id=s[".id"];if(!id)continue;await c.command("/ip/hotspot/active/remove",[`=.id=${id}`]);changed++;}return{message:`تم فصل ${changed} جلسة للمستخدم ${action.target_value}.`,changed};}
    if(action.action_type==="disable_hotspot_user"||action.action_type==="enable_hotspot_user"){const r=await resolveUser(c,action.target_value);if(!r.entry||!r.source)throw new Error("المستخدم لم يعد موجودًا");const id=r.entry[".id"];if(!id)throw new Error("تعذر تحديد ID المستخدم");const enable=action.action_type==="enable_hotspot_user";if(r.source==="hotspot")await c.command(`/ip/hotspot/user/${enable?"enable":"disable"}`,[`=.id=${id}`]);else if(r.source==="user-manager-v6")await c.command(`/tool/user-manager/user/${enable?"enable":"disable"}`,[`=.id=${id}`]);else await c.command("/user-manager/user/set",[`=.id=${id}`,`=disabled=${enable?"no":"yes"}`]);return{message:`تم ${enable?"تفعيل":"تعطيل"} المستخدم ${action.target_value} في ${sourceLabel(r.source)}.`,changed:1};}
    const id=Number(action.target_value);const v=await resolveVlan(c,id);if(!v)throw new Error("VLAN لم يعد موجودًا");const rid=v.row[".id"];if(!rid)throw new Error("تعذر تحديد ID الخاص بـ VLAN");const enable=action.action_type==="enable_vlan";await c.command(`/interface/vlan/${enable?"enable":"disable"}`,[`=.id=${rid}`]);return{message:`تم ${enable?"تفعيل":"تعطيل"} VLAN ${id} (${v.row.name||"-"}).`,changed:1};
  }finally{c.close();}}

export async function handlePrivilegedCallback(update:TgUpdate):Promise<boolean>{const cb=update.callback_query;if(!cb?.data||!/^priv:(?:ok|no):[0-9a-f-]{36}$/i.test(cb.data))return false;const [,decision,id]=cb.data.split(":");const chatId=cb.message?.chat.id??cb.from.id;const messageId=cb.message?.message_id;await answer(cb.id,decision==="ok"?"جاري التحقق…":"تم الإلغاء");const a=(await dbGet<PendingAction>("tg_pending_actions",{id:`eq.${id}`,telegram_user_id:`eq.${cb.from.id}`,select:"*",limit:"1"}))[0];if(!a){await send(chatId,"❌ طلب التأكيد غير موجود أو لا يخص هذا الحساب.");return true;}if(a.status!=="pending"){await send(chatId,`ℹ️ هذا الطلب حالته الآن: <b>${esc(a.status)}</b>.`);return true;}if(new Date(a.expires_at).getTime()<Date.now()){await dbPatch("tg_pending_actions",{status:"expired",completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{id:`eq.${a.id}`,status:"eq.pending"});await audit({telegram_user_id:a.telegram_user_id,chat_id:a.chat_id,network_id:a.network_id,pending_action_id:a.id,action_type:a.action_type,target_type:a.target_type,target_value:a.target_value,phase:"expired"});if(messageId)await edit(chatId,messageId,"⌛ <b>انتهت صلاحية طلب التأكيد.</b>\nأرسل الطلب من جديد إذا ما زلت تريد تنفيذه.");return true;}
  if(decision==="no"){await dbPatch("tg_pending_actions",{status:"cancelled",completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{id:`eq.${a.id}`,status:"eq.pending"});await audit({telegram_user_id:a.telegram_user_id,chat_id:a.chat_id,network_id:a.network_id,pending_action_id:a.id,action_type:a.action_type,target_type:a.target_type,target_value:a.target_value,phase:"cancelled"});if(messageId)await edit(chatId,messageId,`❌ <b>تم الإلغاء</b>\n${esc(actionLabel(a.action_type))} • <code>${esc(a.target_value)}</code>\nلم أغيّر شيئًا في الراوتر.`);return true;}
  const n=(await dbGet<Network>("tg_networks",{id:`eq.${a.network_id}`,telegram_user_id:`eq.${a.telegram_user_id}`,select:"*",limit:"1"}))[0];if(!n){await send(chatId,"❌ الشبكة المرتبطة بهذا الطلب لم تعد موجودة.");return true;}try{await dbPatch("tg_pending_actions",{status:"executing",confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{id:`eq.${a.id}`,status:"eq.pending"});await audit({telegram_user_id:a.telegram_user_id,chat_id:a.chat_id,network_id:a.network_id,pending_action_id:a.id,action_type:a.action_type,target_type:a.target_type,target_value:a.target_value,phase:"confirmed"});await audit({telegram_user_id:a.telegram_user_id,chat_id:a.chat_id,network_id:a.network_id,pending_action_id:a.id,action_type:a.action_type,target_type:a.target_type,target_value:a.target_value,phase:"executing"});if(messageId)await edit(chatId,messageId,`⏳ <b>جاري التنفيذ…</b>\n${esc(actionLabel(a.action_type))} • <code>${esc(a.target_value)}</code>\n📡 ${esc(n.identity||n.label)}`);const result=await execute(a,n);await dbPatch("tg_pending_actions",{status:"success",completed_at:new Date().toISOString(),updated_at:new Date().toISOString(),error_text:null},{id:`eq.${a.id}`});await audit({telegram_user_id:a.telegram_user_id,chat_id:a.chat_id,network_id:a.network_id,pending_action_id:a.id,action_type:a.action_type,target_type:a.target_type,target_value:a.target_value,phase:"success",details:{result}});const text=`✅ <b>تم التنفيذ بنجاح</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n🛠 ${esc(actionLabel(a.action_type))}\n🎯 <code>${esc(a.target_value)}</code>\n\n${esc(result.message)}\n\n🧾 تم تسجيل العملية في Audit Log.`;if(messageId)await edit(chatId,messageId,text);else await send(chatId,text);return true;}catch(e){const error=e instanceof Error?e.message:String(e);await dbPatch("tg_pending_actions",{status:"error",completed_at:new Date().toISOString(),updated_at:new Date().toISOString(),error_text:error.slice(0,1000)},{id:`eq.${a.id}`});await audit({telegram_user_id:a.telegram_user_id,chat_id:a.chat_id,network_id:a.network_id,pending_action_id:a.id,action_type:a.action_type,target_type:a.target_type,target_value:a.target_value,phase:"error",details:{error:error.slice(0,1000)}});const text=`🔴 <b>فشل التنفيذ</b>\nلم أعتبر العملية ناجحة.\n<code>${esc(error)}</code>`;if(messageId)await edit(chatId,messageId,text);else await send(chatId,text);return true;}}

export async function handlePrivilegedNatural(update:TgUpdate):Promise<boolean>{const m=update.message;if(!m?.text||!m.from)return false;const raw=m.text.trim();if(!raw)return false;const ctx=await nluContext(m.from.id);const parsed=parseAction(raw,ctx);if(!parsed)return false;return createPreview(update,parsed);}
