import { createHash, randomBytes } from "crypto";
import { encryptSecret } from "./telegram-crypto";
import { dbGet, dbInsert, dbPatch } from "./telegram-db";
import { normalizeLocalText } from "./telegram-nlu-v2";
import type { TgUpdate } from "./telegram-extra";

type Op="add_user"|"change_profile"|"change_password"|"delete_user";
type BotUser={telegram_user_id:number;active_network_id?:string|null;setup_state?:string|null};
type Network={id:string;telegram_user_id:number;label:string;identity?:string|null;connection_mode:"direct"|"agent";agent_privileged_enabled?:boolean;agent_user_admin_enabled?:boolean;agent_last_seen_at?:string|null};
type Session={id:string;telegram_user_id:number;chat_id:number;network_id:string;operation:Op;username:string;source?:string|null;customer?:string|null;profiles:string[];selected_profile?:string|null;password_ciphertext?:string|null;step:string;expires_at:string;created_at:string};

function token(){const v=process.env.TELEGRAM_BOT_TOKEN;if(!v)throw new Error("TELEGRAM_BOT_TOKEN missing");return v;}
function esc(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
async function tg(method:string,payload:Record<string,unknown>){const r=await fetch(`https://api.telegram.org/bot${token()}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const j=await r.json();if(!j.ok)throw new Error(j.description||`Telegram ${r.status}`);return j.result;}
function send(chatId:number,text:string,reply_markup?:unknown){return tg("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}
async function edit(chatId:number,messageId:number,text:string,reply_markup?:unknown){try{return await tg("editMessageText",{chat_id:chatId,message_id:messageId,text,parse_mode:"HTML",disable_web_page_preview:true,reply_markup});}catch{return null;}}
async function answer(id:string,text?:string,alert=false){try{await tg("answerCallbackQuery",{callback_query_id:id,text,show_alert:alert});}catch{}}
async function del(chatId:number,messageId:number){try{await tg("deleteMessage",{chat_id:chatId,message_id:messageId});}catch{}}
function hash(v:string){return createHash("sha256").update(v).digest("hex");}
async function ctx(uid:number){const u=(await dbGet<BotUser>("tg_users",{telegram_user_id:`eq.${uid}`,select:"telegram_user_id,active_network_id,setup_state",limit:"1"}))[0];if(!u?.active_network_id)return{user:u,network:null};const n=(await dbGet<Network>("tg_networks",{id:`eq.${u.active_network_id}`,telegram_user_id:`eq.${uid}`,select:"id,telegram_user_id,label,identity,connection_mode,agent_privileged_enabled,agent_user_admin_enabled,agent_last_seen_at",limit:"1"}))[0]??null;return{user:u,network:n};}
function cleanUser(v?:string|null){if(!v)return null;const x=v.trim().replace(/^["'«]+|["'»،,.!?]+$/g,"");return /^[\p{L}\p{N}_.@:+-]{2,128}$/u.test(x)?x:null;}
function userFrom(raw:string){const q=cleanUser(raw.match(/["'«]([^"'»]{2,128})["'»]/u)?.[1]);if(q)return q;const n=raw.match(/(?:مستخدم|المستخدم|يوزر|اليوزر|كرت|الكرت|مشترك|user|card|account)\s*(?:رقم|اسم|اسمه|name|number)?\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{2,128})/iu)?.[1];if(n)return cleanUser(n);const parts=raw.trim().split(/\s+/);if(/^\/(?:adduser|profile|setprofile|password|passwd|setpass|deleteuser|deluser|removeuser)$/i.test(parts[0]||"")&&parts[1])return cleanUser(parts[1]);if(/^\/user$/i.test(parts[0]||"")&&parts[2])return cleanUser(parts[2]);return null;}
function profileHint(raw:string,username:string){const i=raw.toLowerCase().indexOf(username.toLowerCase());if(i<0)return null;const after=raw.slice(i+username.length);return after.match(/(?:الى|إلى|الي|على|باقة|باقه|بروفايل|profile|plan|to)\s*[:#-]?\s*([\p{L}\p{N}_.@:+-]{1,128})/iu)?.[1]||null;}
function parse(raw:string):{op:Op;username:string;profile?:string|null}|null{const n=normalizeLocalText(raw);let op:Op|null=null;if(/(?:اضف|أضف|انشئ|أنشئ|سوي|اعمل|create|add)\s*(?:لي\s*)?(?:مستخدم|يوزر|كرت|user|card)/iu.test(n)||/^\/(?:adduser|newuser)\b/i.test(raw)||/^\/user\s+add\b/i.test(raw))op="add_user";else if(/(?:غير|غيّر|بدل|حول|حوّل|change|switch)\s*(?:لي\s*)?(?:الباقه|الباقة|البروفايل|بروفايل|profile|plan)/iu.test(n)||/^\/(?:profile|setprofile)\b/i.test(raw)||/^\/user\s+profile\b/i.test(raw))op="change_profile";else if(/(?:غير|غيّر|بدل|reset|change)\s*(?:لي\s*)?(?:كلمه\s*المرور|كلمة\s*المرور|الباسورد|باسورد|password|passwd|pass)/iu.test(n)||/^\/(?:password|passwd|setpass)\b/i.test(raw)||/^\/user\s+(?:password|passwd)\b/i.test(raw))op="change_password";else if(/(?:احذف|حذف|امسح|مسح|شيل|ازل|remove|delete)\s*(?:لي\s*)?(?:المستخدم|مستخدم|اليوزر|يوزر|الكرت|كرت|user|card|account)/iu.test(n)||/^\/(?:deleteuser|deluser|removeuser)\b/i.test(raw)||/^\/user\s+(?:delete|remove)\b/i.test(raw))op="delete_user";if(!op)return null;const username=userFrom(raw);if(!username)return null;return{op,username,profile:op==="change_profile"||op==="add_user"?profileHint(raw,username):null};}
function installKb(id:string){return{inline_keyboard:[[{text:"🧩 تجهيز User Admin Extension",callback_data:`aua:install:${id}`}],[{text:"❌ إلغاء",callback_data:`aua:noinstall:${id}`}]]};}
function profileKb(s:Session){const bs=(s.profiles||[]).slice(0,20).map((p,i)=>({text:p,callback_data:`aua:p:${s.id}:${i}`}));const rows=[] as Array<Array<{text:string;callback_data:string}>>;for(let i=0;i<bs.length;i+=2)rows.push(bs.slice(i,i+2));rows.push([{text:"❌ إلغاء",callback_data:`aua:no:${s.id}`}]);return{inline_keyboard:rows};}
function passKb(s:Session){return{inline_keyboard:[[{text:"🔑 نفس اسم المستخدم",callback_data:`aua:same:${s.id}`}],[{text:"✍️ كلمة مرور جديدة",callback_data:`aua:custom:${s.id}`}],[{text:"❌ إلغاء",callback_data:`aua:no:${s.id}`}]]};}
function confirmKb(s:Session,label:string,deleteStage=false){return{inline_keyboard:[[{text:label,callback_data:`aua:${deleteStage?"del1":"ok"}:${s.id}`}],[{text:"❌ إلغاء",callback_data:`aua:no:${s.id}`}]]};}
function delete2Kb(s:Session){return{inline_keyboard:[[{text:"🗑 نعم، احذف نهائيًا",callback_data:`aua:del2:${s.id}`}],[{text:"❌ تراجع",callback_data:`aua:no:${s.id}`}]]};}
async function audit(s:Session,phase:string,details:Record<string,unknown>={}){await dbInsert("tg_action_audit",{telegram_user_id:s.telegram_user_id,chat_id:s.chat_id,network_id:s.network_id,pending_action_id:null,action_type:`agent_${s.operation}`,target_type:"user",target_value:s.username,phase,details});}
async function queue(s:Session,kind:string,payload:Record<string,unknown>,replyMessageId?:number|null){await dbInsert("tg_agent_user_admin_commands",{network_id:s.network_id,telegram_user_id:s.telegram_user_id,chat_id:s.chat_id,reply_message_id:replyMessageId||null,kind,payload:{...payload,session_id:s.id},status:"pending"});}
async function start(update:TgUpdate,req:{op:Op;username:string;profile?:string|null},network:Network){const m=update.message;if(!m?.from)return true;const old=await dbGet<Session>("tg_agent_user_admin_sessions",{telegram_user_id:`eq.${m.from.id}`,step:"in.(starting,choose_profile,choose_password,await_password,confirm,delete_stage2)",select:"*",limit:"20"});for(const x of old)await dbPatch("tg_agent_user_admin_sessions",{step:"cancelled",updated_at:new Date().toISOString()},{id:`eq.${x.id}`});const rows=await dbInsert<Session>("tg_agent_user_admin_sessions",{telegram_user_id:m.from.id,chat_id:m.chat.id,network_id:network.id,operation:req.op,username:req.username,selected_profile:req.profile||null,step:"starting"},"*");const s=rows[0];if(!s)throw new Error("تعذر إنشاء جلسة الإدارة");await audit(s,"started",{transport:"agent-user-admin"});const wait=await send(m.chat.id,`🔎 <b>${esc(network.identity||network.label)}</b>\n${req.op==="add_user"?"أقرأ الباقات وطريقة إدارة المستخدمين":"أفحص المستخدم قبل تجهيز التغيير"}…`);await queue(s,req.op==="add_user"?"meta":"preview",{username:req.username},wait.message_id);return true;}
async function awaiting(uid:number){return (await dbGet<Session>("tg_agent_user_admin_sessions",{telegram_user_id:`eq.${uid}`,step:"eq.await_password",select:"*",order:"created_at.desc",limit:"1"}))[0]??null;}
async function session(id:string,uid:number){return (await dbGet<Session>("tg_agent_user_admin_sessions",{id:`eq.${id}`,telegram_user_id:`eq.${uid}`,select:"*",limit:"1"}))[0]??null;}
async function showConfirm(s:Session,chatId:number,messageId?:number){let text=`🛡 <b>تأكيد مطلوب</b>\n━━━━━━━━━━━━━━━━━━\n👤 <code>${esc(s.username)}</code>\n📚 ${esc(s.source||"-")}`;let label="✅ تنفيذ";if(s.operation==="add_user"){text+=`\n🏷 الباقة: <b>${esc(s.selected_profile||"-")}</b>\n🔑 كلمة المرور: محفوظة ومخفية\n\nسيتم إنشاء المستخدم الآن.`;label="✅ إنشاء المستخدم";}else if(s.operation==="change_profile"){text+=`\n➡️ الباقة الجديدة: <b>${esc(s.selected_profile||"-")}</b>\n\nلن أفصل الجلسة الحالية تلقائيًا.`;label="✅ غيّر الباقة";}else if(s.operation==="change_password"){text+=`\n🔑 كلمة المرور الجديدة: محفوظة ومخفية\n\nلن تظهر كلمة المرور في Poll أو Audit.`;label="✅ غيّر كلمة المرور";}else{text+=`\n\n⚠️ الحذف نهائي من قاعدة المستخدمين وسيتم فصل أي جلسة Hotspot نشطة.`;label="⚠️ متابعة الحذف";}await dbPatch("tg_agent_user_admin_sessions",{step:s.operation==="delete_user"?"confirm":"confirm",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});if(messageId)await edit(chatId,messageId,text,confirmKb(s,label,s.operation==="delete_user"));else await send(chatId,text,confirmKb(s,label,s.operation==="delete_user"));}
async function execute(s:Session,messageId?:number){let kind="";const payload:Record<string,unknown>={username:s.username,source:s.source||"",customer:s.customer||""};if(s.operation==="add_user"){kind="add_user";payload.profile=s.selected_profile||"";payload.password_ciphertext=s.password_ciphertext||"";}if(s.operation==="change_profile"){kind="change_profile";payload.profile=s.selected_profile||"";}if(s.operation==="change_password"){kind="change_password";payload.password_ciphertext=s.password_ciphertext||"";}if(s.operation==="delete_user")kind="delete_user";if(!kind)throw new Error("عملية غير معروفة");await dbPatch("tg_agent_user_admin_sessions",{step:"executing",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await audit(s,"confirmed",{source:s.source,profile:s.selected_profile||null,secret:s.operation==="change_password"||s.operation==="add_user"?"one-time":null});await queue(s,kind,payload,messageId||null);}
async function callbacks(update:TgUpdate){const cb=update.callback_query;if(!cb?.data||!cb.data.startsWith("aua:"))return false;const parts=cb.data.split(":");const kind=parts[1];const chatId=cb.message?.chat.id??cb.from.id;const mid=cb.message?.message_id;if(kind==="install"||kind==="noinstall"){const networkId=parts[2]||"";const c=await ctx(cb.from.id);const n=c.network;if(!n||n.id!==networkId||n.connection_mode!=="agent"){await answer(cb.id,"الشبكة غير متاحة",true);return true;}if(kind==="noinstall"){await answer(cb.id,"تم الإلغاء");if(mid)await edit(chatId,mid,"❌ لم يتم تثبيت User Admin Extension.");return true;}const raw=randomBytes(24).toString("base64url");await dbInsert("tg_agent_install_tokens",{network_id:n.id,telegram_user_id:cb.from.id,purpose:"user-admin",token_hash:hash(raw)});const url=`https://mikro-nine.vercel.app/api/router-agent/user-admin/install?network=${encodeURIComponent(n.id)}&install=${encodeURIComponent(raw)}`;const command=`/tool fetch url=\"${url}\" dst-path=mt-tg-user-admin.rsc; /import file-name=mt-tg-user-admin.rsc; /file remove mt-tg-user-admin.rsc`;await answer(cb.id,"جهزت أمر التثبيت");if(mid)await edit(chatId,mid,`🧩 <b>User Admin Extension</b>\n━━━━━━━━━━━━━━━━━━\n📡 ${esc(n.identity||n.label)}\n\nنفّذ هذا الأمر مرة واحدة على MikroTik خلال 10 دقائق:\n\n<code>${esc(command)}</code>\n\nبعدها أعد طلب إدارة المستخدم. Token التثبيت مؤقت ولمرة واحدة.`);return true;}
  const id=parts[2]||"";const s=await session(id,cb.from.id);if(!s){await answer(cb.id,"الجلسة غير موجودة",true);return true;}if(new Date(s.expires_at).getTime()<Date.now()){await dbPatch("tg_agent_user_admin_sessions",{step:"expired",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"انتهت الجلسة",true);return true;}if(kind==="no"){await dbPatch("tg_agent_user_admin_sessions",{step:"cancelled",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await audit(s,"cancelled");await answer(cb.id,"تم الإلغاء");if(mid)await edit(chatId,mid,"❌ تم الإلغاء. لم يتغير شيء على الراوتر.");return true;}if(kind==="p"){const idx=Number(parts[3]);const selected=s.profiles?.[idx];if(!selected){await answer(cb.id,"الباقة غير موجودة",true);return true;}const next={...s,selected_profile:selected};await dbPatch("tg_agent_user_admin_sessions",{selected_profile:selected,step:s.operation==="add_user"?"choose_password":"confirm",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"تم اختيار الباقة");if(s.operation==="add_user"){if(mid)await edit(chatId,mid,`➕ <b>إضافة ${esc(s.username)}</b>\n🏷 الباقة: <b>${esc(selected)}</b>\n\nاختر كلمة المرور:`,passKb(next));}else await showConfirm(next,chatId,mid);return true;}if(kind==="same"){const cipher=encryptSecret(s.username);const next={...s,password_ciphertext:cipher};await dbPatch("tg_agent_user_admin_sessions",{password_ciphertext:cipher,step:"confirm",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"تم");await showConfirm(next,chatId,mid);return true;}if(kind==="custom"){await dbPatch("tg_agent_user_admin_sessions",{step:"await_password",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"أرسل كلمة المرور");if(mid)await edit(chatId,mid,`🔐 أرسل كلمة المرور الجديدة الآن برسالة منفصلة.\nسأحذف الرسالة فور استقبالها وأخزنها مشفرة فقط.`);return true;}if(kind==="del1"){await dbPatch("tg_agent_user_admin_sessions",{step:"delete_stage2",updated_at:new Date().toISOString()},{id:`eq.${s.id}`});await answer(cb.id,"تأكيد أخير");if(mid)await edit(chatId,mid,`🚨 <b>التأكيد الأخير</b>\nسيتم حذف <code>${esc(s.username)}</code> نهائيًا وفصل جلساته النشطة.\n\nلا يوجد Undo تلقائي بعد الحذف.`,delete2Kb(s));return true;}if(kind==="ok"||kind==="del2"){await answer(cb.id,"بدأ التنفيذ");if(mid)await edit(chatId,mid,`⏳ أنفذ العملية على <code>${esc(s.username)}</code> عبر User Admin Extension…`);await execute(s,mid);return true;}return false;}

export async function handleTelegramAgentUserAdmin(update:TgUpdate):Promise<boolean>{if(await callbacks(update))return true;const m=update.message;if(!m?.from||!m.text)return false;const c=await ctx(m.from.id);if(c.user?.setup_state&&c.user.setup_state!=="idle")return false;const pending=await awaiting(m.from.id);if(pending){await del(m.chat.id,m.message_id);const pwd=m.text.trim();if(!pwd||pwd.length>256){await send(m.chat.id,"⚠️ كلمة المرور غير صالحة. أرسل قيمة من 1 إلى 256 حرفًا.");return true;}const cipher=encryptSecret(pwd);const next={...pending,password_ciphertext:cipher};await dbPatch("tg_agent_user_admin_sessions",{password_ciphertext:cipher,step:"confirm",updated_at:new Date().toISOString()},{id:`eq.${pending.id}`});await audit(pending,"secret_received",{stored:"encrypted",message_deleted:true});await showConfirm(next,m.chat.id);return true;}const req=parse(m.text);if(!req)return false;const n=c.network;if(!n||n.connection_mode!=="agent")return false;if(!n.agent_privileged_enabled){await send(m.chat.id,`🔒 <b>هذه العملية تحتاج Privileged Agent</b>\nفعّل التحكم الكامل أولًا بكتابة <code>/agent_privileged</code>. لن أرفع صلاحيات الراوتر تلقائيًا.`);return true;}if(!n.agent_user_admin_enabled){await send(m.chat.id,`🧩 <b>User Admin Extension غير مثبت</b>\n━━━━━━━━━━━━━━━━━━\nلأمان أعلى، إدارة المستخدمين الحساسة تعمل في Extension منفصل عن Agent المراقبة.\n\nثبّته مرة واحدة فقط:`,installKb(n.id));return true;}return start(update,req,n);}
