import { NextResponse } from "next/server";
import { understandProfessionalMessage, type ProIntent } from "@/lib/telegram-nlu-pro";
import type { LocalNluContext } from "@/lib/telegram-nlu-v2";
export const runtime="nodejs"; export const dynamic="force-dynamic";
type C={text:string;intent:ProIntent;card?:string;task?:string;backup?:string;context?:LocalNluContext};
const cases:C[]=[
{text:"افحص الكرت AB-12_X",intent:"card",card:"AB-12_X"},{text:"شيك اليوزر user_ABC",intent:"card",card:"user_ABC"},{text:"افحص ABDULLAH",intent:"card",card:"ABDULLAH"},{text:"افحص عبدالله",intent:"card",card:"عبدالله"},{text:"راجع لي كرت A9Z77",intent:"card",card:"A9Z77"},{text:"card root.admin",intent:"card",card:"root.admin"},{text:"شوف المستخدم vip-user",intent:"card",card:"vip-user"},{text:"15352951",intent:"card",card:"15352951"},{text:"A9Z77",intent:"card",card:"A9Z77"},
{text:"افحص الشبكة",intent:"diagnose"},{text:"شيك النت",intent:"diagnose"},{text:"افحص الراوتر",intent:"router"},{text:"شوف الانترنت يقطع",intent:"diagnose"},
{text:"خذ نسخة rsc",intent:"backup",backup:"rsc"},{text:"سويلي نسخة RSC وارسلها",intent:"backup",backup:"rsc"},{text:"اعمل لي باك اب",intent:"backup"},{text:"نسخة binary",intent:"backup",backup:"binary"},{text:"سوي system backup",intent:"backup",backup:"binary"},{text:"خذ نسخه احتياطية من الاعدادات",intent:"backup"},
{text:"كل يوم الساعة 3 الفجر خذ نسخة rsc",intent:"schedule",task:"backup_rsc"},{text:"كل 6 ساعات ارسل تقرير الحالة",intent:"schedule",task:"status"},{text:"كل ساعتين مبيعات اليوم",intent:"schedule",task:"sales"},{text:"كل يوم الساعة 8 صباح ارسل تقرير الحالة",intent:"schedule",task:"status"},{text:"كل جمعه الساعة 8 صباح ارسل تقرير الحالة",intent:"schedule",task:"status"},{text:"كل 12 ساعات افحص الشبكة",intent:"schedule",task:"diagnose"},{text:"كل يوم الساعة 2 بالليل سوي binary backup",intent:"schedule",task:"backup_binary"},
{text:"جدولي",intent:"show_schedules"},{text:"المهام المجدولة",intent:"show_schedules"},{text:"الغ الجدول 2",intent:"cancel_schedule"},
{text:"جيب اخر اخطاء الراوتر",intent:"logs"},{text:"اعرض الانترفيسات",intent:"interfaces"},{text:"كم DHCP lease عندي",intent:"dhcp"},{text:"وش وضع الهوتسبوت",intent:"hotspot"},{text:"مين اكثر واحد يستهلك",intent:"top_usage"},
{text:"كم في مستخدمين الان",intent:"online"},{text:"كم بعنا اليوم",intent:"sales"},{text:"vlan 202",intent:"vlan_detail"},{text:"اعرض الفيلانات",intent:"vlans"},{text:"كم الرام",intent:"router"},{text:"اختبر البنج",intent:"ping"},{text:"كيف الشبكة",intent:"status"},{text:"النت بطيء افحصه",intent:"diagnose"},{text:"شبكاتي",intent:"networks"},{text:"استخدم الثانية",intent:"use_network"},{text:"اضف شبكة",intent:"add_network"},{text:"الغاء",intent:"cancel"},{text:"وش تقدر تسوي",intent:"help"},{text:"هلا",intent:"greeting"},{text:"شكرا",intent:"thanks"},
{text:"وش اخر جلسة",intent:"card",context:{last_intent:"card",last_entity_type:"card",last_entity_value:"AB-12_X"}},{text:"كم استهلاكها",intent:"vlan_detail",context:{last_intent:"vlan_detail",last_entity_type:"vlan",last_entity_value:"202"}}
];
export async function GET(){const rows=cases.map(c=>{const r=understandProfessionalMessage(c.text,c.context);const ok=r.intent===c.intent&&(!c.card||r.entities.card===c.card)&&(!c.task||r.entities.scheduled_task===c.task)&&(!c.backup||r.entities.backup_type===c.backup);return {text:c.text,expected:c.intent,got:r.intent,card:r.entities.card,task:r.entities.scheduled_task,backup:r.entities.backup_type,confidence:r.confidence,ok};});const passed=rows.filter(x=>x.ok).length;return NextResponse.json({total:rows.length,passed,accuracy:Number((passed/rows.length*100).toFixed(2)),failures:rows.filter(x=>!x.ok)});}
